import { BackgroundData } from '../types';

export const BACKGROUNDS: { [key: string]: BackgroundData } = {
    "Acolyte": { skills: ["Insight", "Religion"], gear: "Holy Symbol, Prayer Book", feature: "Shelter of the Faithful" },
    "Soldier": { skills: ["Athletics", "Intimidation"], gear: "Insignia of Rank, Trophy", feature: "Military Rank" },
    "Criminal": { skills: ["Deception", "Stealth"], gear: "Crowbar, Dark Clothes", feature: "Criminal Contact" },
    "Folk Hero": { skills: ["Animal Handling", "Survival"], gear: "Shovel, Iron Pot", feature: "Rustic Hospitality" },
    "Sage": { skills: ["Arcana", "History"], gear: "Bottle of Ink, Quill", feature: "Researcher" },
    "Charlatan": { skills: ["Deception", "Sleight of Hand"], gear: "Fine Clothes, Disguise Kit", feature: "False Identity" },
    "Hermit": { skills: ["Medicine", "Religion"], gear: "Herbalism Kit, Common Clothes", feature: "Discovery" },
    "Urchin": { skills: ["Sleight of Hand", "Stealth"], gear: "Small Knife, Map of the City, Tattered Clothes", feature: "City Secrets" },
    "Guild Artisan": { skills: ["Insight", "Persuasion"], gear: "Artisan's Tools, Letter of Introduction, Fine Clothes", feature: "Guild Membership" },
    "Noble": { skills: ["History", "Persuasion"], gear: "Fine Clothes, Signet Ring, Scroll of Pedigree", feature: "Position of Privilege" },
    "Sailor": { skills: ["Athletics", "Perception"], gear: "Belaying Pin, Rope (50ft), Lucky Charm", feature: "Ship's Passage" },

    // === Additional Backgrounds ===
    "Entertainer": { skills: ["Acrobatics", "Performance"], gear: "Lute, Fine Clothes, Disguise Kit", feature: "By Popular Demand" },
    "Outlander": { skills: ["Athletics", "Survival"], gear: "Staff, Hunting Trap, Trophy", feature: "Wanderer" },
    "Pirate": { skills: ["Athletics", "Perception"], gear: "Belaying Pin, Rope (50ft), Lucky Charm", feature: "Bad Reputation" },
    "Spy": { skills: ["Deception", "Stealth"], gear: "Disguise Kit, Thieves' Tools, Dark Clothes", feature: "False Identity" },
    "Bounty Hunter": { skills: ["Investigation", "Survival"], gear: "Rope (50ft), Manacles, Dagger", feature: "Ear to the Ground" },
    "Gladiator": { skills: ["Acrobatics", "Performance"], gear: "Trident, Trophy, Fine Clothes", feature: "By Popular Demand" },
    "Knight": { skills: ["History", "Persuasion"], gear: "Signet Ring, Banner, Fine Clothes", feature: "Retainers" },
    "Courtier": { skills: ["Insight", "Persuasion"], gear: "Fine Clothes, Scroll of Pedigree, Signet Ring", feature: "Court Functionary" },
    "Far Traveler": { skills: ["Insight", "Perception"], gear: "Musical Instrument, Maps, Fine Clothes", feature: "All Eyes on You" },
    "Haunted One": { skills: ["Arcana", "Investigation"], gear: "Chest, Crowbar, Trinket from Monster", feature: "Heart of Darkness" },
    "Anthropologist": { skills: ["Insight", "Religion"], gear: "Leather Diary, Ink, Quill", feature: "Adept Linguist" },
    "Archaeologist": { skills: ["History", "Survival"], gear: "Wooden Case, Map, Brush", feature: "Historical Knowledge" },
    "City Watch": { skills: ["Athletics", "Insight"], gear: "Uniform, Horn, Manacles", feature: "Watcher's Eye" },
    "Clan Crafter": { skills: ["History", "Insight"], gear: "Artisan's Tools, Maker's Mark, Fine Clothes", feature: "Respect of the Stout Folk" },
    "Cloistered Scholar": { skills: ["History", "Religion"], gear: "Scholar's Robes, Quill, Ink, Parchment", feature: "Library Access" },
    "Faction Agent": { skills: ["Insight", "Investigation"], gear: "Badge, Copy of Faction's Text, Common Clothes", feature: "Safe Haven" },
    "Inheritor": { skills: ["Survival", "History"], gear: "Inheritance (Special Item), Fine Clothes", feature: "Inheritance" },
    "Mercenary Veteran": { skills: ["Athletics", "Persuasion"], gear: "Uniform, Insignia, Gaming Set", feature: "Mercenary Life" },
    "Urban Bounty Hunter": { skills: ["Investigation", "Stealth"], gear: "Appropriate Clothes, Manacles", feature: "Ear to the Ground" },
    "Waterdhavian Noble": { skills: ["History", "Persuasion"], gear: "Fine Clothes, Signet Ring, Scroll of Pedigree", feature: "Kept in Style" },
    "Acolyte of the Temple": { skills: ["Insight", "Religion"], gear: "Holy Symbol, Prayer Wheel, Vestments", feature: "Temple Services" },
    "Failed Merchant": { skills: ["Investigation", "Persuasion"], gear: "Mule, Cart, Ledger", feature: "Supply Chain" },
    "Gambler": { skills: ["Deception", "Insight"], gear: "Dice Set, Fine Clothes, Lucky Charm", feature: "Never Tell Me the Odds" },
    "Grinner": { skills: ["Deception", "Performance"], gear: "Disguise Kit, Musical Instrument, Fine Clothes", feature: "Ballad of the Grinning Fool" },
    "Celebrity Adventurer": { skills: ["Performance", "Persuasion"], gear: "Autograph Book, Fine Clothes, Portrait", feature: "Name Dropping" },
    "House Agent": { skills: ["Investigation", "Persuasion"], gear: "House Signet, Fine Clothes, Documents", feature: "House Connections" },
    "Marine": { skills: ["Athletics", "Survival"], gear: "Dagger, Folded Flag, Uniform", feature: "Hardship Endured" },
    "Shipwright": { skills: ["History", "Perception"], gear: "Carpenter's Tools, Hammer, Wood Planks", feature: "I'll Patch It!" },
    "Smuggler": { skills: ["Athletics", "Deception"], gear: "Dark Clothes, Rope, Signal Lantern", feature: "Down Low" }
};