import { ClassData } from '../types';

export const CLASSES: { [key: string]: ClassData } = {
  "Fighter": { hd: 10, mana: 0, stamina: 15, gear: "Chain Mail, Iron Longsword, Wooden Shield", savingThrows: ["str", "con"], skills: ["Acrobatics", "Athletics"], features: ["Second Wind", "Fighting Style"], primaryStats: ['str', 'con'], startingLocation: "Barracks Town" }, 
  "Wizard": { hd: 6, mana: 15, stamina: 5, gear: "Robes, Staff, Book", savingThrows: ["int", "wis"], skills: ["Arcana", "History"], features: ["Spellcasting", "Arcane Recovery"], primaryStats: ['int', 'wis'], spells: ['firebolt', 'shield'], startingLocation: "Arcane Academy" }, 
  "Rogue": { hd: 8, mana: 0, stamina: 12, gear: "Leather Armor, Dagger", savingThrows: ["dex", "int"], skills: ["Acrobatics", "Stealth", "Sleight of Hand"], features: ["Sneak Attack", "Thieves' Cant"], primaryStats: ['dex', 'cha'], startingLocation: "Thieves' Guild Hideout" }, 
  "Cleric": { hd: 8, mana: 12, stamina: 8, gear: "Scale Mail, Mace", savingThrows: ["wis", "cha"], skills: ["Insight", "Religion"], features: ["Spellcasting", "Divine Domain"], primaryStats: ['wis', 'cha'], spells: ['heal'], startingLocation: "Temple Village" }, 
  "Barbarian": { hd: 12, mana: 0, stamina: 15, gear: "Hide Armor, Axe", savingThrows: ["str", "con"], skills: ["Athletics", "Survival"], features: ["Rage", "Unarmored Defense"], primaryStats: ['str', 'con'], startingLocation: "Nomad Camp" }, 
  "Ranger": { hd: 10, mana: 6, stamina: 10, gear: "Leather Armor, Bow", savingThrows: ["str", "dex"], skills: ["Animal Handling", "Survival"], features: ["Favored Enemy", "Natural Explorer"], primaryStats: ['dex', 'wis'], startingLocation: "Forest Outpost" }, 
  "Paladin": { hd: 10, mana: 6, stamina: 10, gear: "Chain Mail, Hammer", savingThrows: ["wis", "cha"], skills: ["Athletics", "Persuasion"], features: ["Divine Sense", "Lay on Hands"], primaryStats: ['str', 'cha'], spells: ['heal'], startingLocation: "Holy Bastion" }, 
  "Monk": { hd: 8, mana: 4, stamina: 15, gear: "Robes, Staff", savingThrows: ["str", "dex"], skills: ["Acrobatics", "Insight"], features: ["Unarmored Defense", "Martial Arts"], primaryStats: ['dex', 'wis'], startingLocation: "Mountain Monastery" }, 
  "Sorcerer": { hd: 6, mana: 15, stamina: 3, gear: "Dagger, Arcane Focus", savingThrows: ["con", "cha"], skills: ["Arcana", "Deception"], features: ["Spellcasting", "Sorcerous Origin"], primaryStats: ['cha', 'con'], spells: ['firebolt'], startingLocation: "Hidden Cove" }, 
  "Warlock": { hd: 8, mana: 10, stamina: 5, gear: "Spear, Component Pouch", savingThrows: ["wis", "cha"], skills: ["Arcana", "Intimidation"], features: ["Otherworldly Patron", "Pact Magic"], primaryStats: ['cha', 'int'], spells: ['firebolt'], startingLocation: "Forbidden Library" }, 
  "Artificer": { hd: 8, mana: 8, stamina: 5, gear: "Thieves' Tools, Crossbow", savingThrows: ["con", "int"], skills: ["Arcana", "Investigation"], features: ["Magical Tinkering", "Infuse Item"], primaryStats: ['int', 'con'], spells: ['firebolt'], startingLocation: "Clockwork City" }, 
  "Bard": { hd: 8, mana: 12, stamina: 5, gear: "Lute, Leather Armor", savingThrows: ["dex", "cha"], skills: ["Performance", "Persuasion"], features: ["Bardic Inspiration", "Spellcasting"], primaryStats: ['cha', 'dex'], spells: ['heal'], startingLocation: "Bustling Metropolis" }, 
  "Druid": { hd: 8, mana: 12, stamina: 5, gear: "Scimitar, Wooden Shield", savingThrows: ["int", "wis"], skills: ["Nature", "Survival"], features: ["Druidic", "Spellcasting"], primaryStats: ['wis', 'con'], spells: ['heal'], startingLocation: "Sacred Grove" }
};