import { Enemy } from '../types';

export const ENEMIES_DB: Enemy[] = [
    // === CR 0 - 1/4 (Weak Enemies) ===
    { id: 'rat', name: "Giant Rat", type: "beast", challenge: 0.125, hp: 7, hpMax: 7, ac: 12, damageRoll: "1d4", speed: 30, xp: 25, loot: ['ration'], description: "A dog-sized rat with mange-ridden fur and gleaming red eyes." },
    { id: 'bat_swarm', name: "Swarm of Bats", type: "beast", challenge: 0.25, hp: 22, hpMax: 22, ac: 12, damageRoll: "2d4", speed: 30, xp: 50, resistances: ["bludgeoning", "piercing", "slashing"], description: "A writhing cloud of screeching bats." },
    { id: 'goblin', name: "Goblin", type: "humanoid", challenge: 0.25, hp: 7, hpMax: 7, ac: 15, damageRoll: "1d6+2", speed: 30, xp: 50, abilities: ["Nimble Escape"], loot: ['dagger_standard', 'ration'], description: "A small, green-skinned creature with sharp teeth and cunning eyes." },
    { id: 'kobold', name: "Kobold", type: "humanoid", challenge: 0.125, hp: 5, hpMax: 5, ac: 12, damageRoll: "1d4+2", speed: 30, xp: 25, abilities: ["Pack Tactics", "Sunlight Sensitivity"], loot: ['dagger_standard'], description: "A small reptilian humanoid with a yipping voice." },
    { id: 'skeleton', name: "Skeleton", type: "undead", challenge: 0.25, hp: 13, hpMax: 13, ac: 13, damageRoll: "1d6+2", speed: 30, xp: 50, immunities: ["poison"], vulnerabilities: ["bludgeoning"], loot: ['sword_iron'], description: "Animated bones held together by dark magic." },
    { id: 'zombie', name: "Zombie", type: "undead", challenge: 0.25, hp: 22, hpMax: 22, ac: 8, damageRoll: "1d6+1", speed: 20, xp: 50, immunities: ["poison"], abilities: ["Undead Fortitude"], description: "A shambling corpse with rotting flesh and empty eyes." },
    { id: 'wolf', name: "Wolf", type: "beast", challenge: 0.25, hp: 11, hpMax: 11, ac: 13, damageRoll: "2d4+2", speed: 40, xp: 50, abilities: ["Pack Tactics"], description: "A gray wolf with keen senses and sharp fangs." },
    { id: 'giant_spider', name: "Giant Spider", type: "beast", challenge: 0.25, hp: 26, hpMax: 26, ac: 14, damageRoll: "1d8+3", speed: 30, xp: 50, abilities: ["Web Walker", "Web Sense"], description: "A massive spider the size of a horse." },
 
    // === CR 1/2 - 1 (Common Enemies) ===
    { id: 'orc', name: "Orc", type: "humanoid", challenge: 0.5, hp: 15, hpMax: 15, ac: 13, damageRoll: "1d12+3", speed: 30, xp: 100, abilities: ["Aggressive"], loot: ['axe_standard', 'ration'], description: "A hulking gray-skinned warrior with tusks and tribal scars." },
    { id: 'hobgoblin', name: "Hobgoblin", type: "humanoid", challenge: 0.5, hp: 11, hpMax: 11, ac: 18, damageRoll: "1d8+1", speed: 30, xp: 100, abilities: ["Martial Advantage"], loot: ['sword_iron', 'armor_chain_mail'], description: "A disciplined goblinoid soldier in well-maintained armor." },
    { id: 'gnoll', name: "Gnoll", type: "humanoid", challenge: 0.5, hp: 22, hpMax: 22, ac: 15, damageRoll: "1d8+2", speed: 30, xp: 100, abilities: ["Rampage"], loot: ['spear_standard'], description: "A hyena-headed savage driven by endless hunger." },
    { id: 'shadow', name: "Shadow", type: "undead", challenge: 0.5, hp: 16, hpMax: 16, ac: 12, damageRoll: "2d6+2", speed: 40, xp: 100, immunities: ["necrotic", "poison"], resistances: ["acid", "cold", "fire", "lightning", "thunder"], abilities: ["Strength Drain", "Shadow Stealth"], description: "A dark, incorporeal shape that drains the life from the living." },
    { id: 'bugbear', name: "Bugbear", type: "humanoid", challenge: 1, hp: 27, hpMax: 27, ac: 16, damageRoll: "2d8+2", speed: 30, xp: 200, abilities: ["Surprise Attack", "Brute"], loot: ['axe_great', 'pot_heal'], description: "A massive, hairy goblinoid that strikes from ambush." },
    { id: 'dire_wolf', name: "Dire Wolf", type: "beast", challenge: 1, hp: 37, hpMax: 37, ac: 14, damageRoll: "2d6+3", speed: 50, xp: 200, abilities: ["Pack Tactics", "Keen Hearing and Smell"], description: "An enormous wolf, large enough to serve as a mount." },
    { id: 'ghoul', name: "Ghoul", type: "undead", challenge: 1, hp: 22, hpMax: 22, ac: 12, damageRoll: "2d6+2", speed: 30, xp: 200, immunities: ["poison", "charmed", "exhaustion"], abilities: ["Paralyzing Touch"], description: "An undead creature that feeds on the flesh of corpses." },
    { id: 'specter', name: "Specter", type: "undead", challenge: 1, hp: 22, hpMax: 22, ac: 12, damageRoll: "3d6", speed: 50, xp: 200, immunities: ["necrotic", "poison"], resistances: ["acid", "cold", "fire", "lightning", "thunder"], abilities: ["Life Drain", "Incorporeal Movement"], description: "A hateful spirit bound to the material world by rage." },
    { id: 'harpy', name: "Harpy", type: "monstrosity", challenge: 1, hp: 38, hpMax: 38, ac: 11, damageRoll: "2d4+1", speed: 40, xp: 200, abilities: ["Luring Song"], description: "A winged creature with a woman's face and a vulture's body." },
    { id: 'drowned_sailor', name: "Drowned Sailor", type: "undead", challenge: 1, hp: 30, hpMax: 30, ac: 12, damageRoll: "1d8+2", speed: 20, xp: 200, immunities: ["poison"], resistances: ["cold"], abilities: ["Waterlogged Grip"], loot: ['storm_lantern', 'ration'], description: "A sodden corpse animated by brine and resentment, clutching rusted gear." },
 
    // === CR 2-3 (Challenging Enemies) ===
    { id: 'ogre', name: "Ogre", type: "giant", challenge: 2, hp: 59, hpMax: 59, ac: 11, damageRoll: "2d8+4", speed: 40, xp: 450, loot: ['axe_great', 'pot_heal', 'ration'], description: "A dim-witted brute standing ten feet tall with yellowed tusks." },
    { id: 'gargoyle', name: "Gargoyle", type: "elemental", challenge: 2, hp: 52, hpMax: 52, ac: 15, damageRoll: "2d6+2", speed: 60, xp: 450, immunities: ["poison"], resistances: ["bludgeoning", "piercing", "slashing"], abilities: ["False Appearance"], description: "A stone creature that lurks on castle walls, frozen until prey arrives." },
    { id: 'ghast', name: "Ghast", type: "undead", challenge: 2, hp: 36, hpMax: 36, ac: 13, damageRoll: "2d8+3", speed: 30, xp: 450, immunities: ["poison"], abilities: ["Stench", "Paralyzing Touch"], description: "A more powerful ghoul that exudes a nauseating stench." },
    { id: 'mimic', name: "Mimic", type: "monstrosity", challenge: 2, hp: 58, hpMax: 58, ac: 12, damageRoll: "1d8+3", speed: 15, xp: 450, abilities: ["Shapechanger", "Adhesive", "Grappler"], loot: ['ring_protection', 'pot_heal'], description: "A shapeshifting predator that disguises itself as treasure chests." },
    { id: 'reef_stalker', name: "Reef Stalker", type: "monstrosity", challenge: 2, hp: 44, hpMax: 44, ac: 14, damageRoll: "2d6+3", speed: 40, xp: 450, abilities: ["Ambush", "Saltwater Camouflage"], loot: ['mariners_compass', 'dried_meat'], description: "A sleek, coral-skinned predator that blends with tide pools before striking." },
    { id: 'werewolf', name: "Werewolf", type: "humanoid", challenge: 3, hp: 58, hpMax: 58, ac: 12, damageRoll: "2d4+3", speed: 40, xp: 700, immunities: ["bludgeoning", "piercing", "slashing"], abilities: ["Shapechanger", "Keen Hearing and Smell"], description: "A cursed human that transforms into a savage wolf-like beast." },
    { id: 'owlbear', name: "Owlbear", type: "monstrosity", challenge: 3, hp: 59, hpMax: 59, ac: 13, damageRoll: "2d8+4", speed: 40, xp: 700, abilities: ["Keen Sight and Smell"], description: "A fearsome hybrid with an owl's head and a bear's body." },
    { id: 'manticore', name: "Manticore", type: "monstrosity", challenge: 3, hp: 68, hpMax: 68, ac: 14, damageRoll: "2d6+3", speed: 50, xp: 700, abilities: ["Tail Spike Regrowth"], description: "A lion with bat wings and a tail covered in deadly spikes." },
    { id: 'wight', name: "Wight", type: "undead", challenge: 3, hp: 45, hpMax: 45, ac: 14, damageRoll: "1d8+2", speed: 30, xp: 700, immunities: ["poison", "necrotic"], abilities: ["Life Drain", "Sunlight Sensitivity"], loot: ['sword_iron', 'armor_chain_mail'], description: "An intelligent undead warrior animated by hatred of the living." },
    { id: 'basilisk', name: "Basilisk", type: "monstrosity", challenge: 3, hp: 52, hpMax: 52, ac: 15, damageRoll: "2d6+3", speed: 20, xp: 700, abilities: ["Petrifying Gaze"], description: "An eight-legged reptile whose gaze turns creatures to stone." },

    // === CR 4-5 (Dangerous Enemies) ===
    { id: 'ettin', name: "Ettin", type: "giant", challenge: 4, hp: 85, hpMax: 85, ac: 12, damageRoll: "2d8+5", speed: 40, xp: 1100, abilities: ["Two Heads", "Wakeful"], loot: ['axe_great', 'pot_heal'], description: "A two-headed giant, each head with its own vile personality." },
    { id: 'ghost', name: "Ghost", type: "undead", challenge: 4, hp: 45, hpMax: 45, ac: 11, damageRoll: "4d6+3", speed: 40, xp: 1100, immunities: ["cold", "necrotic", "poison"], resistances: ["acid", "fire", "lightning", "thunder"], abilities: ["Etherealness", "Horrifying Visage", "Possession"], description: "The restless spirit of a tormented soul, seeking peace or vengeance." },
    { id: 'flameskull', name: "Flameskull", type: "undead", challenge: 4, hp: 40, hpMax: 40, ac: 13, damageRoll: "3d6", speed: 40, xp: 1100, immunities: ["cold", "fire", "lightning", "necrotic", "poison"], abilities: ["Illumination", "Magic Resistance", "Rejuvenation"], description: "A floating skull wreathed in green flames, hurling fire at intruders." },
    { id: 'troll', name: "Troll", type: "giant", challenge: 5, hp: 84, hpMax: 84, ac: 15, damageRoll: "2d6+4", speed: 30, xp: 1800, abilities: ["Keen Smell", "Regeneration"], vulnerabilities: ["fire", "acid"], description: "A lanky green-skinned brute that regenerates even the most grievous wounds." },
    { id: 'wraith', name: "Wraith", type: "undead", challenge: 5, hp: 67, hpMax: 67, ac: 13, damageRoll: "4d8+3", speed: 60, xp: 1800, immunities: ["necrotic", "poison"], resistances: ["acid", "cold", "fire", "lightning", "thunder"], abilities: ["Life Drain", "Create Specter", "Incorporeal Movement"], description: "A powerful undead spirit cloaked in shadows and hatred." },
    { id: 'salamander', name: "Salamander", type: "elemental", challenge: 5, hp: 90, hpMax: 90, ac: 15, damageRoll: "2d8+3", speed: 30, xp: 1800, immunities: ["fire"], vulnerabilities: ["cold"], abilities: ["Heated Body", "Heated Weapons"], description: "A serpentine elemental from the Plane of Fire." },
    { id: 'hill_giant', name: "Hill Giant", type: "giant", challenge: 5, hp: 105, hpMax: 105, ac: 13, damageRoll: "3d8+5", speed: 40, xp: 1800, loot: ['axe_great', 'pot_heal', 'ration'], description: "A brutish giant with a voracious appetite for destruction." },
    { id: 'vampire_spawn', name: "Vampire Spawn", type: "undead", challenge: 5, hp: 82, hpMax: 82, ac: 15, damageRoll: "2d6+3", speed: 30, xp: 1800, immunities: ["necrotic"], resistances: ["bludgeoning", "piercing", "slashing"], abilities: ["Regeneration", "Spider Climb", "Vampire Weaknesses"], description: "A newly-turned vampire, thrall to a more powerful master." },

    // === CR 6-8 (Very Dangerous Enemies) ===
    { id: 'medusa', name: "Medusa", type: "monstrosity", challenge: 6, hp: 127, hpMax: 127, ac: 15, damageRoll: "2d6+2", speed: 30, xp: 2300, abilities: ["Petrifying Gaze"], loot: ['ring_protection', 'amulet_health'], description: "A cursed woman with snakes for hair and a petrifying gaze." },
    { id: 'cyclops', name: "Cyclops", type: "giant", challenge: 6, hp: 138, hpMax: 138, ac: 14, damageRoll: "3d8+6", speed: 30, xp: 2300, abilities: ["Poor Depth Perception"], loot: ['axe_great'], description: "A one-eyed giant known for its brute strength and poor judgment." },
    { id: 'chimera', name: "Chimera", type: "monstrosity", challenge: 6, hp: 114, hpMax: 114, ac: 14, damageRoll: "2d6+4", speed: 60, xp: 2300, abilities: ["Fire Breath"], description: "A three-headed beast with a lion, goat, and dragon head." },
    { id: 'young_dragon_black', name: "Young Black Dragon", type: "dragon", challenge: 7, hp: 127, hpMax: 127, ac: 18, damageRoll: "2d10+4", speed: 80, xp: 2900, immunities: ["acid"], abilities: ["Acid Breath", "Amphibious"], loot: ['ring_protection', 'pot_heal'], description: "A vicious dragon that haunts swamps and delights in cruelty." },
    { id: 'young_dragon_green', name: "Young Green Dragon", type: "dragon", challenge: 8, hp: 136, hpMax: 136, ac: 18, damageRoll: "2d10+4", speed: 80, xp: 3900, immunities: ["poison"], abilities: ["Poison Breath", "Amphibious"], loot: ['amulet_health'], description: "A cunning dragon that manipulates lesser creatures for its schemes." },
    { id: 'mind_flayer', name: "Mind Flayer", type: "aberration", challenge: 7, hp: 71, hpMax: 71, ac: 15, damageRoll: "2d10+3", speed: 30, xp: 2900, abilities: ["Mind Blast", "Extract Brain", "Magic Resistance"], description: "An alien creature with a tentacled face that feeds on brains." },
    { id: 'frost_giant', name: "Frost Giant", type: "giant", challenge: 8, hp: 138, hpMax: 138, ac: 15, damageRoll: "3d12+6", speed: 40, xp: 3900, immunities: ["cold"], loot: ['axe_great', 'pot_heal'], description: "A massive giant from frozen lands, wielding an enormous axe." },
    { id: 'stone_giant', name: "Stone Giant", type: "giant", challenge: 7, hp: 126, hpMax: 126, ac: 17, damageRoll: "3d8+6", speed: 40, xp: 2900, abilities: ["Stone Camouflage"], description: "A reclusive giant that hurls boulders with deadly accuracy." },

    // === CR 9-12 (Deadly Enemies) ===
    { id: 'fire_giant', name: "Fire Giant", type: "giant", challenge: 9, hp: 162, hpMax: 162, ac: 18, damageRoll: "3d12+7", speed: 30, xp: 5000, immunities: ["fire"], abilities: ["Heated Body"], loot: ['armor_plate', 'axe_great'], description: "A brutal giant smith wreathed in flames and hatred." },
    { id: 'bone_devil', name: "Bone Devil", type: "fiend", challenge: 9, hp: 142, hpMax: 142, ac: 19, damageRoll: "3d8+5", speed: 40, xp: 5000, immunities: ["fire", "poison"], resistances: ["cold"], abilities: ["Devil's Sight", "Magic Resistance"], description: "A skeletal fiend that serves as a lieutenant of Hell." },
    { id: 'cloud_giant', name: "Cloud Giant", type: "giant", challenge: 9, hp: 200, hpMax: 200, ac: 14, damageRoll: "3d8+8", speed: 40, xp: 5000, abilities: ["Keen Smell", "Innate Spellcasting"], loot: ['armor_plate', 'ring_protection'], description: "A giant dwelling among the clouds, wielding powerful magic." },
    { id: 'adult_dragon_white', name: "Adult White Dragon", type: "dragon", challenge: 10, hp: 200, hpMax: 200, ac: 18, damageRoll: "2d10+6", speed: 80, xp: 5900, immunities: ["cold"], abilities: ["Cold Breath", "Ice Walk"], loot: ['armor_plate', 'ring_protection', 'amulet_health'], description: "A savage dragon of the frozen north, driven by animal cunning." },
    { id: 'beholder', name: "Beholder", type: "aberration", challenge: 13, hp: 180, hpMax: 180, ac: 18, damageRoll: "4d8+4", speed: 20, xp: 10000, abilities: ["Antimagic Cone", "Eye Rays"], loot: ['ring_protection', 'amulet_health', 'pot_heal'], description: "A floating orb of hatred with a central eye and many eyestalks." },
    { id: 'adult_dragon_red', name: "Adult Red Dragon", type: "dragon", challenge: 17, hp: 256, hpMax: 256, ac: 19, damageRoll: "2d10+8", speed: 80, xp: 18000, immunities: ["fire"], abilities: ["Fire Breath", "Legendary Resistance", "Frightful Presence"], loot: ['armor_plate', 'ring_protection', 'amulet_health'], description: "The most fearsome of dragons, a tyrant of flame and destruction." },
    { id: 'lich', name: "Lich", type: "undead", challenge: 21, hp: 135, hpMax: 135, ac: 17, damageRoll: "3d6", speed: 30, xp: 33000, immunities: ["poison", "necrotic"], abilities: ["Legendary Resistance", "Rejuvenation", "Spellcasting", "Paralyzing Touch"], loot: ['ring_protection', 'amulet_health', 'spellbook'], description: "An undead archmage who achieved immortality through dark rituals." },
    { id: 'ancient_dragon_gold', name: "Ancient Gold Dragon", type: "dragon", challenge: 24, hp: 546, hpMax: 546, ac: 22, damageRoll: "2d10+10", speed: 80, xp: 62000, immunities: ["fire"], abilities: ["Fire Breath", "Weakening Breath", "Legendary Resistance", "Frightful Presence", "Change Shape"], description: "A benevolent but terrifyingly powerful ancient wyrm." },
    { id: 'tarrasque', name: "Tarrasque", type: "monstrosity", challenge: 30, hp: 676, hpMax: 676, ac: 25, damageRoll: "4d12+10", speed: 40, xp: 155000, immunities: ["fire", "poison"], abilities: ["Legendary Resistance", "Magic Resistance", "Reflective Carapace", "Siege Monster"], description: "The most dreaded creature in existence, a world-ending titan." },
];
