export const FEATS_DB = [ 
    { id: 'alert', name: "Alert", desc: "+5 Initiative, cannot be surprised.", req: "None" }, 
    { id: 'tough', name: "Tough", desc: "+2 HP per level.", req: "None" },
    { id: 'charger', name: "Charger", desc: "When you use your action to Dash, you can use a bonus action to make one melee weapon attack or to shove a creature.", req: "None" },
    { id: 'defensive_duelist', name: "Defensive Duelist", desc: "When wielding a finesse weapon, you can use your reaction to add your proficiency bonus to your AC against one melee attack.", req: "Dex 13+" },
    { id: 'great_weapon_master', name: "Great Weapon Master", desc: "Before you make a melee attack with a heavy weapon that you are proficient with, you can choose to take a -5 penalty to the attack roll. If the attack hits, you add +10 to the attack's damage.", req: "None" },
    { id: 'mobile', name: "Mobile", desc: "Your speed increases by 10 feet. When you make a melee attack against a creature, you don't provoke opportunity attacks from that creature for the rest of the turn.", req: "None" },
    { id: 'sentinel', name: "Sentinel", desc: "When you hit a creature with an opportunity attack, its speed becomes 0 for the rest of the turn. Creatures provoke opportunity attacks from you even if they take the Disengage action. When a creature within 5 feet of you makes an attack against a target other than you, you can use your reaction to make a melee weapon attack against the attacking creature.", req: "None" },
    { id: 'sharpshooter', name: "Sharpshooter", desc: "Before you make an attack with a ranged weapon that you are proficient with, you can choose to take a -5 penalty to the attack roll. If the attack hits, you add +10 to the attack's damage. Attacking at long range doesn't impose disadvantage on your ranged weapon attack rolls. Your ranged weapon attacks ignore half cover and three-quarters cover.", req: "None" },
    { id: 'war_caster', name: "War Caster", desc: "You have advantage on Constitution saving throws that you make to maintain your concentration on a spell. You can perform the somatic components of spells even when you have weapons or a shield in one or both hands. When a hostile creature's movement provokes an opportunity attack from you, you can use your reaction to cast a spell at the creature, instead of making an opportunity attack. The spell must have a casting time of 1 action and must target only that creature.", req: "Ability to cast at least one spell" }
];