export const FEATS_DB = [
    // === COMBAT FEATS ===
    { id: 'alert', name: "Alert", desc: "+5 Initiative, cannot be surprised.", req: "None" },
    { id: 'tough', name: "Tough", desc: "+2 HP per level.", req: "None" },
    { id: 'charger', name: "Charger", desc: "When you use your action to Dash, you can use a bonus action to make one melee weapon attack or to shove a creature.", req: "None" },
    { id: 'defensive_duelist', name: "Defensive Duelist", desc: "When wielding a finesse weapon, you can use your reaction to add your proficiency bonus to your AC against one melee attack.", req: "Dex 13+" },
    { id: 'great_weapon_master', name: "Great Weapon Master", desc: "Before you make a melee attack with a heavy weapon that you are proficient with, you can choose to take a -5 penalty to the attack roll. If the attack hits, you add +10 to the attack's damage.", req: "None" },
    { id: 'mobile', name: "Mobile", desc: "Your speed increases by 10 feet. When you make a melee attack against a creature, you don't provoke opportunity attacks from that creature for the rest of the turn.", req: "None" },
    { id: 'sentinel', name: "Sentinel", desc: "When you hit a creature with an opportunity attack, its speed becomes 0 for the rest of the turn. Creatures provoke opportunity attacks from you even if they take the Disengage action. When a creature within 5 feet of you makes an attack against a target other than you, you can use your reaction to make a melee weapon attack against the attacking creature.", req: "None" },
    { id: 'sharpshooter', name: "Sharpshooter", desc: "Before you make an attack with a ranged weapon that you are proficient with, you can choose to take a -5 penalty to the attack roll. If the attack hits, you add +10 to the attack's damage. Attacking at long range doesn't impose disadvantage on your ranged weapon attack rolls. Your ranged weapon attacks ignore half cover and three-quarters cover.", req: "None" },
    { id: 'war_caster', name: "War Caster", desc: "You have advantage on Constitution saving throws that you make to maintain your concentration on a spell. You can perform the somatic components of spells even when you have weapons or a shield in one or both hands. When a hostile creature's movement provokes an opportunity attack from you, you can use your reaction to cast a spell at the creature, instead of making an opportunity attack. The spell must have a casting time of 1 action and must target only that creature.", req: "Ability to cast at least one spell" },
    { id: 'dual_wielder', name: "Dual Wielder", desc: "+1 AC while wielding two weapons. You can wield non-light weapons in both hands. You can draw or stow two weapons at once.", req: "None" },
    { id: 'savage_attacker', name: "Savage Attacker", desc: "Once per turn when you roll damage for a melee weapon attack, you can reroll the damage dice and use either total.", req: "None" },
    { id: 'polearm_master', name: "Polearm Master", desc: "When you take the Attack action with a glaive, halberd, quarterstaff, or spear, you can use a bonus action to make an additional attack with the opposite end of the weapon. Creatures provoke opportunity attacks when entering your reach.", req: "None" },
    { id: 'shield_master', name: "Shield Master", desc: "If you take the Attack action, you can use a bonus action to shove with your shield. You can add your shield's AC bonus to Dexterity saving throws. If you succeed on a Dexterity save, you can use your reaction to take no damage.", req: "None" },
    { id: 'crossbow_expert', name: "Crossbow Expert", desc: "You ignore the loading property of crossbows. Being within 5 feet of a hostile creature doesn't impose disadvantage on ranged attacks. When you take the Attack action with a one-handed weapon, you can use a bonus action to attack with a hand crossbow.", req: "None" },
    { id: 'grappler', name: "Grappler", desc: "You have advantage on attack rolls against a creature you are grappling. You can use your action to pin a grappled creature, restraining both of you.", req: "Str 13+" },
    { id: 'tavern_brawler', name: "Tavern Brawler", desc: "+1 Strength or Constitution. You are proficient with improvised weapons. Your unarmed strike deals 1d4 damage. When you hit with an unarmed strike or improvised weapon, you can grapple as a bonus action.", req: "None" },
    { id: 'heavy_armor_master', name: "Heavy Armor Master", desc: "+1 Strength. While wearing heavy armor, reduce bludgeoning, piercing, and slashing damage from nonmagical weapons by 3.", req: "Heavy Armor Proficiency" },
    { id: 'medium_armor_master', name: "Medium Armor Master", desc: "Wearing medium armor doesn't impose disadvantage on Stealth. You can add up to +3 Dexterity modifier to AC in medium armor.", req: "Medium Armor Proficiency" },
    { id: 'mounted_combatant', name: "Mounted Combatant", desc: "You have advantage on melee attacks against unmounted creatures smaller than your mount. You can force attacks targeting your mount to target you instead. Your mount takes no damage on successful Dexterity saves, half on failures.", req: "None" },
    { id: 'mage_slayer', name: "Mage Slayer", desc: "When a creature within 5 feet casts a spell, you can use your reaction to attack them. Creatures you damage have disadvantage on concentration saves. You have advantage on saves against spells cast by creatures within 5 feet.", req: "None" },
    { id: 'martial_adept', name: "Martial Adept", desc: "You learn two maneuvers from the Battle Master archetype and gain one superiority die (d6) that you recover on a short or long rest.", req: "None" },
    { id: 'lucky', name: "Lucky", desc: "You have 3 luck points. When you make an attack roll, ability check, or saving throw, you can spend one to roll an additional d20 and choose which to use. When attacked, you can spend one to make the attacker reroll.", req: "None" },

    // === MAGIC FEATS ===
    { id: 'spell_sniper', name: "Spell Sniper", desc: "Spells requiring attack rolls have double range. Your spell attacks ignore half and three-quarters cover. You learn one cantrip requiring an attack roll.", req: "Ability to cast at least one spell" },
    { id: 'elemental_adept', name: "Elemental Adept", desc: "Choose a damage type: acid, cold, fire, lightning, or thunder. Spells you cast ignore resistance to that damage type. When rolling damage for a spell of that type, treat any 1 as a 2.", req: "Ability to cast at least one spell" },
    { id: 'ritual_caster', name: "Ritual Caster", desc: "You gain a ritual book containing two 1st-level spells with the ritual tag. You can cast these spells as rituals and add more ritual spells to your book.", req: "Int or Wis 13+" },
    { id: 'magic_initiate', name: "Magic Initiate", desc: "Choose a spellcasting class. You learn two cantrips and one 1st-level spell from that class's spell list, which you can cast once per long rest.", req: "None" },
    { id: 'fey_touched', name: "Fey Touched", desc: "+1 Intelligence, Wisdom, or Charisma. You learn Misty Step and one 1st-level divination or enchantment spell. You can cast each once per long rest or with spell slots.", req: "None" },
    { id: 'shadow_touched', name: "Shadow Touched", desc: "+1 Intelligence, Wisdom, or Charisma. You learn Invisibility and one 1st-level illusion or necromancy spell. You can cast each once per long rest or with spell slots.", req: "None" },
    { id: 'telekinetic', name: "Telekinetic", desc: "+1 Intelligence, Wisdom, or Charisma. You learn Mage Hand (invisible). As a bonus action, you can shove a creature within 30 feet 5 feet toward or away from you.", req: "None" },
    { id: 'telepathic', name: "Telepathic", desc: "+1 Intelligence, Wisdom, or Charisma. You can speak telepathically to creatures within 60 feet. You can cast Detect Thoughts once per long rest.", req: "None" },
    { id: 'metamagic_adept', name: "Metamagic Adept", desc: "You learn two Metamagic options from the sorcerer class and gain 2 sorcery points to fuel them, recovering on a long rest.", req: "Ability to cast at least one spell" },

    // === SKILL & UTILITY FEATS ===
    { id: 'observant', name: "Observant", desc: "+1 Intelligence or Wisdom. You can read lips. +5 to passive Perception and Investigation.", req: "None" },
    { id: 'skulker', name: "Skulker", desc: "You can try to hide when lightly obscured. Missing a ranged attack doesn't reveal your position. Dim light doesn't impose disadvantage on Perception checks.", req: "Dex 13+" },
    { id: 'athlete', name: "Athlete", desc: "+1 Strength or Dexterity. Standing up uses only 5 feet of movement. Climbing doesn't halve your speed. You can make running long jumps and high jumps with only 5 feet of movement.", req: "None" },
    { id: 'actor', name: "Actor", desc: "+1 Charisma. You have advantage on Deception and Performance checks when trying to pass yourself off as a different person. You can mimic the speech of others or sounds you've heard.", req: "None" },
    { id: 'keen_mind', name: "Keen Mind", desc: "+1 Intelligence. You always know which way is north and how many hours until sunrise or sunset. You can accurately recall anything you've seen or heard within the past month.", req: "None" },
    { id: 'linguist', name: "Linguist", desc: "+1 Intelligence. You learn three languages. You can create written ciphers that others can't decipher without the key or an Intelligence check.", req: "None" },
    { id: 'skilled', name: "Skilled", desc: "You gain proficiency in any combination of three skills or tools of your choice.", req: "None" },
    { id: 'prodigy', name: "Prodigy", desc: "You gain proficiency in one skill, one tool, and one language. You gain expertise in one skill you're proficient with.", req: "Human or Half-Elf or Half-Orc" },
    { id: 'dungeon_delver', name: "Dungeon Delver", desc: "You have advantage on Perception and Investigation checks to detect secret doors. You have advantage on saves against traps and resistance to trap damage. Travelling at a fast pace doesn't impose a penalty to passive Perception.", req: "None" },

    // === DEFENSIVE FEATS ===
    { id: 'resilient', name: "Resilient", desc: "+1 to one ability score. You gain proficiency in saving throws using that ability.", req: "None" },
    { id: 'durable', name: "Durable", desc: "+1 Constitution. When you roll Hit Dice to regain HP, the minimum you can roll is twice your Constitution modifier.", req: "None" },
    { id: 'inspiring_leader', name: "Inspiring Leader", desc: "You can spend 10 minutes inspiring companions. Up to 6 friendly creatures gain temporary HP equal to your level + Charisma modifier.", req: "Cha 13+" },
    { id: 'healer', name: "Healer", desc: "When you use a healer's kit to stabilize a creature, they also regain 1 HP. You can use an action and a healer's kit to restore 1d6+4+creature's max Hit Dice in HP.", req: "None" },

    // === RACIAL FEATS ===
    { id: 'elven_accuracy', name: "Elven Accuracy", desc: "+1 Dexterity, Intelligence, Wisdom, or Charisma. When you have advantage on an attack using Dex, Int, Wis, or Cha, you can reroll one of the dice once.", req: "Elf or Half-Elf" },
    { id: 'orcish_fury', name: "Orcish Fury", desc: "+1 Strength or Constitution. Once per rest, when you hit with a weapon attack, you can roll one additional damage die. When you use Relentless Endurance, you can make a weapon attack as a reaction.", req: "Half-Orc" },
    { id: 'dragon_fear', name: "Dragon Fear", desc: "+1 Strength, Constitution, or Charisma. Instead of exhaling destructive energy, you can roar, causing creatures within 30 feet to make a Wisdom save or be frightened.", req: "Dragonborn" },
    { id: 'dragon_hide', name: "Dragon Hide", desc: "+1 Strength, Constitution, or Charisma. Your scales harden; when unarmored, your AC is 13 + Dexterity modifier. You grow retractable claws that deal 1d4 slashing damage.", req: "Dragonborn" },
    { id: 'dwarven_fortitude', name: "Dwarven Fortitude", desc: "+1 Constitution. When you take the Dodge action in combat, you can spend one Hit Die to heal yourself.", req: "Dwarf" },
    { id: 'squat_nimbleness', name: "Squat Nimbleness", desc: "+1 Strength or Dexterity. Your walking speed increases by 5 feet. You gain proficiency in Acrobatics or Athletics. You have advantage on checks to escape grapples.", req: "Dwarf or Halfling or Gnome" },
    { id: 'infernal_constitution', name: "Infernal Constitution", desc: "+1 Constitution. You have resistance to cold and poison damage. You have advantage on saving throws against being poisoned.", req: "Tiefling" },
    { id: 'second_chance', name: "Second Chance", desc: "+1 Dexterity, Constitution, or Charisma. When a creature you can see hits you with an attack, you can use your reaction to force them to reroll. Once used, you can't use it again until you roll initiative.", req: "Halfling" },
    { id: 'bountiful_luck', name: "Bountiful Luck", desc: "When an ally you can see within 30 feet rolls a 1 on an attack, check, or save, you can use your reaction to let them reroll.", req: "Halfling" },
    { id: 'fade_away', name: "Fade Away", desc: "+1 Dexterity or Intelligence. When you take damage, you can use a reaction to become invisible until the end of your next turn or until you attack or cast a spell.", req: "Gnome" },

    // === LEGENDARY FEATS ===
    { id: 'original_spell_creator', name: "Original Spell Creator", desc: "Your mastery of the arcane or divine arts transcends known magic. You can create entirely new, original spells — designing their effects, naming them, and even teaching them to others. You can also learn original spells created by other spellcasters. Created spells cost 25% less mana to cast. Full power unlocks at 100+ INT or WIS.", req: "Ability to cast at least one spell" }
];