import { Item } from '../types';

export const ITEMS_DB: Item[] = [ 
    // === CONSUMABLES & SURVIVAL ===
    { id: 'pot_heal', name: "Healing Potion", type: "consumable", rarity: "common", value: 500, weight: 0.5, effect: { hp: 10 }, description: "A basic crimson potion that restores a small amount of health." }, 
    { id: 'ration', name: "Ration (Day)", type: "food", rarity: "common", value: 50, weight: 2, effect: { hunger: -1 }, description: "A day's worth of dried meat, hardtack, and fruit." }, 
    { id: 'waterskin', name: "Waterskin (Full)", type: "water", rarity: "common", value: 20, weight: 5, effect: { thirst: -0.5 }, description: "A simple leather pouch filled with fresh water." }, 
    
    // === MUNDANE GEAR ===
    // Weapons
    { id: 'sword_iron', name: "Iron Longsword", type: "weapon", rarity: "common", slot: "mainHand", damageRoll: "1d8", weight: 3, value: 1000, description: "A standard longsword, reliable in combat." }, 
    { id: 'axe_standard', name: "Axe", type: "weapon", rarity: "common", slot: "mainHand", twoHanded: true, damageRoll: "1d12", weight: 7, value: 1500, description: "A heavy greataxe, capable of cleaving through foes." }, 
    { id: 'dagger_standard', name: "Dagger", type: "weapon", rarity: "common", slot: "mainHand", damageRoll: "1d4", weight: 1, value: 200, description: "A small, sharp blade, good for close quarters or throwing." },
    { id: 'mace_standard', name: "Mace", type: "weapon", rarity: "common", slot: "mainHand", damageRoll: "1d6", weight: 4, value: 500, description: "A stout bludgeoning weapon." },
    { id: 'bow_standard', name: "Bow", type: "weapon", rarity: "common", slot: "mainHand", twoHanded: true, damageRoll: "1d6", weight: 2, value: 2500, description: "A simple shortbow for ranged attacks." },
    { id: 'staff_standard', name: "Staff", type: "weapon", rarity: "common", slot: "mainHand", twoHanded: true, damageRoll: "1d6", weight: 4, value: 50, description: "A sturdy wooden staff, useful as a walking stick or a simple weapon." },
    { id: 'hammer_standard', name: "Hammer", type: "weapon", rarity: "common", slot: "mainHand", damageRoll: "1d8", weight: 2, value: 1500, description: "A warhammer, excellent for crushing blows." },
    { id: 'scimitar_standard', name: "Scimitar", type: "weapon", rarity: "common", slot: "mainHand", damageRoll: "1d6", weight: 3, value: 2500, description: "A curved sword, favored by skirmishers." },
    { id: 'spear_standard', name: "Spear", type: "weapon", rarity: "common", slot: "mainHand", damageRoll: "1d6", weight: 3, value: 100, description: "A simple thrusting weapon." },
    { id: 'harpoon', name: "Harpoon", type: "weapon", rarity: "common", slot: "mainHand", damageRoll: "1d8", weight: 5, value: 1800, description: "A barbed weapon designed for hauling sea beasts or foes from the surf." },
    { id: 'crossbow_standard', name: "Crossbow", type: "weapon", rarity: "common", slot: "mainHand", twoHanded: true, damageRoll: "1d8", weight: 5, value: 2500, description: "A light crossbow for ranged combat." },
    { id: 'small_knife', name: "Small Knife", type: "weapon", rarity: "common", slot: "mainHand", damageRoll: "1d4", weight: 0.5, value: 100, description: "A basic utility knife, not meant for combat but can be used as a last resort." },
    { id: 'belaying_pin', name: "Belaying Pin", type: "weapon", rarity: "common", slot: "mainHand", damageRoll: "1d4", weight: 2, value: 50, description: "A heavy wooden pin used on ships, surprisingly effective in a brawl." },
    { id: 'axe_great', name: "Great Axe", type: "weapon", rarity: "common", slot: "mainHand", twoHanded: true, damageRoll: "1d12", weight: 7, value: 2000, description: "A massive, two-handed axe, capable of devastating swings." },
    
    // Armor
    { id: 'armor_leather', name: "Leather Armor", type: "armor", rarity: "common", slot: "chest", ac: 11, weight: 10, value: 1000, description: "Light armor made from hardened leather." },
    { id: 'armor_chain_mail', name: "Chain Mail", type: "armor", rarity: "common", slot: "chest", ac: 16, weight: 55, value: 7500, description: "Heavy armor consisting of interlocking metal rings." },
    { id: 'armor_scale_mail', name: "Scale Mail", type: "armor", rarity: "common", slot: "chest", ac: 14, weight: 45, value: 5000, description: "Medium armor made from overlapping metal scales." },
    { id: 'armor_hide', name: "Hide Armor", type: "armor", rarity: "common", slot: "chest", ac: 12, weight: 12, value: 1000, description: "Crude armor made from thick animal hides." },
    { id: 'armor_robes', name: "Robes", type: "armor", rarity: "common", slot: "chest", ac: 10, weight: 4, value: 100, description: "Loose-fitting garments, offering little protection but favored by mages." },
    { id: 'armor_common_clothes', name: "Common Clothes", type: "armor", rarity: "common", slot: "chest", ac: 10, weight: 3, value: 10, description: "Everyday wear for the common folk." },
    { id: 'armor_tattered_clothes', name: "Tattered Clothes", type: "armor", rarity: "common", slot: "chest", ac: 10, weight: 2, value: 5, description: "Worn and torn garments, offering minimal warmth and protection." },
    { id: 'cloak_saltward', name: "Saltward Cloak", type: "armor", rarity: "common", slot: "cloak", ac: 0, weight: 1, value: 600, description: "A weatherproof cloak treated with sea-salt oils to keep spray and chill at bay." },
    { id: 'shield_wooden', name: "Wooden Shield", type: "armor", rarity: "common", slot: "offHand", ac: 2, weight: 6, value: 1000, description: "A simple wooden shield, provides basic defense." },
    { id: 'shield_steel', name: "Steel Shield", type: "armor", rarity: "common", slot: "offHand", ac: 2, weight: 6, value: 1000, description: "A sturdy steel shield, offering reliable protection." },
    { id: 'armor_plate', name: "Plate Armor", type: "armor", rarity: "rare", slot: "chest", ac: 18, weight: 65, value: 150000, description: "Full plate armor, offering the best mundane protection but heavy." },

    // Tools & Professional Gear
    { id: 'thieves_tools', name: "Thieves' Tools", type: "tool", rarity: "common", slot: "belt", weight: 1, value: 2500, description: "A set of lockpicks and other tools for opening locks and disarming traps." },
    { id: 'holy_symbol', name: "Holy Symbol", type: "tool", rarity: "common", slot: "amulet", weight: 1, value: 500, description: "A sacred emblem representing a deity or religious order." },
    { id: 'lute', name: "Lute", type: "tool", rarity: "common", weight: 2, value: 3500, description: "A stringed instrument, often used by bards to entertain." },
    { id: 'arcane_focus', name: "Arcane Focus", type: "tool", rarity: "common", slot: "mainHand", weight: 3, value: 1000, description: "An item used by spellcasters to channel their magic." },
    { id: 'component_pouch', name: "Component Pouch", type: "tool", rarity: "common", slot: "belt", weight: 2, value: 2500, description: "A small pouch filled with various mundane components for spellcasting." },
    { id: 'spellbook', name: "Book", type: "tool", rarity: "common", weight: 3, value: 5000, description: "A tome containing a wizard's spells and arcane notes." },
    { id: 'herbalism_kit', name: "Herbalism Kit", type: "tool", rarity: "common", slot: "belt", weight: 3, value: 5000, description: "A collection of tools for identifying and harvesting herbs." },
    { id: 'artisan_tools', name: "Artisan's Tools", type: "tool", rarity: "common", slot: "hands", weight: 8, value: 5000, description: "A set of tools for a specific craft, such as smithing or carpentry." },
    { id: 'shipwright_tools', name: "Shipwright's Tools", type: "tool", rarity: "common", slot: "hands", weight: 10, value: 6500, description: "A kit of adzes, caulking irons, and tar for repairing hulls and rigging." },
    { id: 'navigation_sextant', name: "Navigation Sextant", type: "tool", rarity: "uncommon", weight: 2, value: 3500, description: "A precision instrument for charting courses by sun and star." },
    { id: 'mariners_compass', name: "Mariner's Compass", type: "tool", rarity: "common", weight: 1, value: 750, description: "A brass compass etched with tide marks, trusted by sailors to find safe waters." },
    { id: 'weighted_net', name: "Weighted Net", type: "tool", rarity: "common", weight: 4, value: 300, description: "A heavy net with lead weights, used to snare quarry or slow foes." },
    { id: 'hull_repair_kit', name: "Hull Repair Kit", type: "tool", rarity: "common", weight: 6, value: 1200, description: "Pitch, wedges, and a mallet for patching leaks and hull damage." },
    { id: 'rope_50ft', name: "Rope (50ft)", type: "tool", rarity: "common", weight: 10, value: 100, description: "Fifty feet of sturdy hempen rope." },
    { id: 'torch', name: "Torch", type: "gear", rarity: "common", weight: 1, value: 10, description: "A wooden stick with a cloth soaked in pitch, provides light." }, 
    { id: 'storm_lantern', name: "Storm Lantern", type: "gear", rarity: "common", weight: 2, value: 350, description: "A hooded lantern with reinforced glass designed to stay lit in high winds." },
    { id: 'rigging_oil', name: "Rigging Oil", type: "gear", rarity: "common", weight: 0.5, value: 180, description: "A tin of oil that keeps ropes and pulleys from fraying." },
    { id: 'anchor_chain', name: "Anchor Chain", type: "gear", rarity: "common", weight: 15, value: 900, description: "A heavy chain used to secure vessels in rough waters." },
    { id: 'sea_chart', name: "Sea Chart", type: "gear", rarity: "common", weight: 0.2, value: 500, description: "A water-stained chart marking shoals, coves, and safe anchorages." },
    { id: 'signal_flare', name: "Signal Flare", type: "consumable", rarity: "common", weight: 0.2, value: 250, description: "A bright flare that can signal allies or ward off predators at sea." },
    { id: 'vial_empty', name: "Empty Vial", type: "gear", rarity: "common", weight: 0.1, value: 10, description: "A small glass container, suitable for potions or liquids." }, 
    { id: 'healing_herb', name: "Healing Herb", type: "crafting", rarity: "common", weight: 0.1, value: 25, description: "Common herbs with minor restorative properties." }, 
    { id: 'herb_healing', name: "Healing Herb Bundle", type: "crafting", rarity: "common", weight: 0.2, value: 50, description: "A bundled harvest of restorative herbs used by apothecaries." },
    { id: 'grain_sack', name: "Sack of Grain", type: "crafting", rarity: "common", weight: 5, value: 30, description: "A sack containing common grains, good for basic sustenance." }, 
    { id: 'dried_meat', name: "Dried Meat", type: "crafting", rarity: "common", weight: 1, value: 40, description: "Preserved meat, a staple for travelers." }, 
    { id: 'leather_hide', name: "Leather Hide", type: "crafting", rarity: "common", weight: 2, value: 100, description: "Raw animal hide, useful for crafting armor or goods." }, 
    { id: 'thread_tough', name: "Tough Thread", type: "crafting", rarity: "common", weight: 0.1, value: 50, description: "Strong, durable thread for stitching and repairs." }, 
    { id: 'iron_ingot', name: "Iron Ingot", type: "crafting", rarity: "common", weight: 5, value: 200, description: "A bar of refined iron, essential for smithing." }, 
    { id: 'wood_scrap', name: "Wood Scraps", type: "crafting", rarity: "common", weight: 1, value: 5, description: "Assorted pieces of wood, useful for small crafts." }, 
    { id: 'gem_dust', name: "Gem Dust", type: "crafting", rarity: "uncommon", weight: 0.1, value: 500, description: "Finely ground precious gems, used in arcane crafts." }, 
    { id: 'poisonous_plant', name: "Poisonous Plant", type: "crafting", rarity: "uncommon", weight: 0.1, value: 150, description: "A plant with toxic properties, used in alchemy." },
    { id: 'pitch', name: "Pitch", type: "crafting", rarity: "common", weight: 1, value: 120, description: "A tar-like resin used to seal hulls and waterproof gear." },
    { id: 'canvas_roll', name: "Canvas Roll", type: "crafting", rarity: "common", weight: 3, value: 200, description: "A roll of durable canvas used for sails and coverings." },
    { id: 'reef_coral', name: "Reef Coral", type: "crafting", rarity: "uncommon", weight: 1, value: 450, description: "A chunk of living coral prized for coastal rituals and alchemy." },
    { id: 'brine_salt', name: "Brine Salt", type: "crafting", rarity: "common", weight: 0.5, value: 80, description: "Sea salt infused with brine, used in preservation and wards." },
    { id: 'ship_planks', name: "Ship Planks", type: "crafting", rarity: "common", weight: 6, value: 250, description: "Seasoned wood planks cut for ship repairs." },
    { id: 'tar_resin', name: "Tar Resin", type: "crafting", rarity: "common", weight: 1, value: 140, description: "Sticky resin used to bind and seal nautical gear." },
    { id: 'pearl_shard', name: "Pearl Shard", type: "crafting", rarity: "uncommon", weight: 0.1, value: 600, description: "A lustrous pearl fragment used in charms and enchantments." },
    { id: 'sea_glass', name: "Sea Glass", type: "crafting", rarity: "common", weight: 0.2, value: 60, description: "Glass worn smooth by tides, used in trinkets and focus lenses." },
    { id: 'glass_shard', name: "Glass Shard", type: "crafting", rarity: "common", weight: 0.1, value: 40, description: "A clean glass fragment suitable for lanterns and small crafts." },
    { id: 'siren_scale', name: "Siren Scale", type: "crafting", rarity: "rare", weight: 0.1, value: 1200, description: "A shimmering scale said to hold echoes of a siren's song." },
    { id: 'driftwood', name: "Driftwood", type: "crafting", rarity: "common", weight: 2, value: 30, description: "Weathered wood carried ashore by tides, useful for basic crafts." },
    { id: 'netting', name: "Netting", type: "crafting", rarity: "common", weight: 1, value: 90, description: "Knotted rope netting used for traps and fishing." },
    { id: 'kelp_fiber', name: "Kelp Fiber", type: "crafting", rarity: "common", weight: 0.5, value: 70, description: "Tough fibers dried from kelp, used in cordage and wraps." },
    { id: 'amber_resin', name: "Amber Resin", type: "crafting", rarity: "uncommon", weight: 0.2, value: 320, description: "Sticky amber resin prized by artisans and alchemists." },
    { id: 'salted_fish', name: "Salted Fish", type: "food", rarity: "common", weight: 1, value: 60, effect: { hunger: -0.5 }, description: "Cured fish packed with salt for long voyages." },
    
    // === BACKGROUND ITEMS ===
    { id: 'bg_prayer_book', name: "Prayer Book", type: "gear", rarity: "common", weight: 5, value: 2500, description: "A worn book of prayers and scripture." },
    { id: 'bg_insignia', name: "Insignia of Rank", type: "gear", rarity: "common", weight: 0.1, value: 50, description: "A symbol of military rank, granting a small degree of authority." },
    { id: 'bg_trophy', name: "Trophy", type: "gear", rarity: "common", weight: 1, value: 10, description: "A small, personal memento of a past victory or achievement." },
    { id: 'bg_crowbar', name: "Crowbar", type: "tool", rarity: "common", weight: 5, value: 200, description: "A versatile tool for prying open stubborn objects." },
    { id: 'bg_dark_clothes', name: "Dark Clothes", type: "armor", rarity: "common", slot: "chest", ac: 10, weight: 3, value: 50, description: "Modest, dark-colored clothing, suitable for blending into shadows." },
    { id: 'bg_fine_clothes', name: "Fine Clothes", type: "armor", rarity: "common", slot: "chest", ac: 10, weight: 6, value: 1500, description: "Well-made clothing suitable for formal occasions." },
    { id: 'bg_shovel', name: "Shovel", type: "tool", rarity: "common", weight: 5, value: 200, description: "A sturdy shovel, useful for digging or as an improvised weapon." },
    { id: 'bg_iron_pot', name: "Iron Pot", type: "gear", rarity: "common", weight: 10, value: 200, description: "A simple iron pot for cooking." },
    { id: 'bg_ink_bottle', name: "Bottle of Ink", type: "gear", rarity: "common", weight: 0.1, value: 1000, description: "A small bottle of black ink." },
    { id: 'bg_quill', name: "Quill", type: "gear", rarity: "common", weight: 0, value: 2, description: "A feather quill for writing." },
    { id: 'bg_disguise_kit', name: "Disguise Kit", type: "tool", rarity: "common", slot: "belt", weight: 3, value: 2500, description: "A collection of makeup, hair dye, and simple props to alter one's appearance." },
    { id: 'bg_rope_silk', name: "Silk Rope (50ft)", type: "tool", rarity: "common", weight: 5, value: 1000, description: "Fifty feet of strong, light silk rope." },
    { id: 'map_of_city', name: "Map of the City", type: "gear", rarity: "common", weight: 0.5, value: 25, description: "A detailed map of a major city, showing streets and landmarks." },
    { id: 'letter_introduction', name: "Letter of Introduction", type: "gear", rarity: "common", weight: 0.1, value: 10, description: "A formal letter endorsing the bearer, useful for gaining access." },
    { id: 'signet_ring', name: "Signet Ring", type: "accessory", rarity: "common", slot: "ring", weight: 0.05, value: 500, description: "A ring bearing a family crest or guild symbol, used for sealing documents." },
    { id: 'scroll_pedigree', name: "Scroll of Pedigree", type: "gear", rarity: "common", weight: 0.1, value: 50, description: "A scroll detailing a noble's lineage and family history." },
    { id: 'lucky_charm', name: "Lucky Charm", type: "accessory", rarity: "common", slot: "amulet", weight: 0.1, value: 100, description: "A small trinket believed to bring good fortune." },
 
    // === MAGICAL WEAPONS ===
    { id: 'sword_flame', name: "Flametongue Sword", type: "weapon", rarity: "rare", slot: "mainHand", power: 6, weight: 3, value: 25000, effect: { fire: 4 }, description: "A blade that erupts in flame with a command word." },
    { id: 'sword_frost', name: "Frostbrand Sword", type: "weapon", rarity: "rare", slot: "mainHand", power: 6, weight: 3, value: 25000, effect: { cold: 4 }, description: "A blade that freezes the air around it." },
    { id: 'sword_vorpal', name: "Vorpal Sword", type: "weapon", rarity: "legendary", slot: "mainHand", power: 10, weight: 3, value: 100000, description: "A legendary blade said to sever heads with a whisper." },
    { id: 'sword_holy', name: "Holy Avenger", type: "weapon", rarity: "legendary", slot: "mainHand", power: 8, weight: 4, value: 80000, effect: { radiant: 6 }, description: "A holy sword that shines with divine light, especially potent against evil." },
    { id: 'dagger_venom', name: "Dagger of Venom", type: "weapon", rarity: "rare", slot: "mainHand", power: 4, weight: 1, value: 15000, effect: { poison: 5 }, description: "A dark blade coated in a potent, recurring poison." },
    { id: 'dagger_assassin', name: "Assassin's Blade", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 1, value: 20000, description: "A wickedly sharp dagger, designed for silent and lethal strikes." },
    { id: 'axe_berserker', name: "Berserker Axe", type: "weapon", rarity: "rare", slot: "mainHand", power: 7, weight: 7, value: 18000, twoHanded: true, description: "A brutal axe that drives its wielder into a frenzied rage." },
    { id: 'hammer_thunder', name: "Hammer of Thunderbolts", type: "weapon", rarity: "legendary", slot: "mainHand", power: 9, weight: 10, value: 75000, effect: { lightning: 6 }, description: "A colossal hammer that can summon crackling storms." },
    { id: 'staff_power', name: "Staff of Power", type: "weapon", rarity: "legendary", slot: "mainHand", power: 5, weight: 5, value: 100000, twoHanded: true, description: "An ancient staff crackling with raw magical energy." },
    { id: 'staff_magi', name: "Staff of the Magi", type: "weapon", rarity: "legendary", slot: "mainHand", power: 6, weight: 5, value: 150000, twoHanded: true, description: "The most powerful of staves, imbued with immense arcane might." },
    { id: 'bow_oath', name: "Oathbow", type: "weapon", rarity: "rare", slot: "mainHand", power: 6, weight: 2, value: 35000, twoHanded: true, description: "A magical longbow that grants its wielder an advantage against a chosen foe." },
    { id: 'bow_lightning', name: "Bow of Lightning", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 2, value: 28000, twoHanded: true, effect: { lightning: 3 }, description: "Each arrow loosed from this bow carries a jolt of electricity." },
    { id: 'trident_fish', name: "Trident of Fish Command", type: "weapon", rarity: "uncommon", slot: "mainHand", power: 4, weight: 4, value: 8000, description: "A trident that allows its wielder to communicate with and command fish." },
    { id: 'mace_disruption', name: "Mace of Disruption", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 4, value: 22000, effect: { radiant: 4 }, description: "A holy mace that burns undead and fiends with radiant light." },
    { id: 'mace_smiting', name: "Mace of Smiting", type: "weapon", rarity: "rare", slot: "mainHand", power: 6, weight: 5, value: 25000, description: "This mace causes its wielder's blows to strike with divine force." },
    { id: 'scimitar_speed', name: "Scimitar of Speed", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 3, value: 30000, description: "A scimitar that grants its wielder incredible swiftness in combat." },
    { id: 'sword_dancing', name: "Dancing Sword", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 3, value: 35000, description: "A sentient sword that can float and fight independently." },
    { id: 'sword_luck', name: "Luck Blade", type: "weapon", rarity: "legendary", slot: "mainHand", power: 6, weight: 3, value: 90000, description: "A legendary blade imbued with incredible luck, able to grant wishes." },
    { id: 'sword_nine', name: "Nine Lives Stealer", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 3, value: 40000, description: "A cursed sword that has claimed many lives, said to steal life force." },
    { id: 'javelin_lightning', name: "Javelin of Lightning", type: "weapon", rarity: "uncommon", slot: "mainHand", power: 4, weight: 2, value: 8000, effect: { lightning: 4 }, description: "A javelin that transforms into a bolt of lightning when thrown." },
 
    // === MAGICAL ARMOR ===
    { id: 'armor_mithral', name: "Mithral Chain Shirt", type: "armor", rarity: "uncommon", slot: "chest", ac: 13, weight: 10, value: 15000, description: "A light and flexible chain shirt made of mithral, reducing its weight." },
    { id: 'armor_adamantine', name: "Adamantine Plate", type: "armor", rarity: "rare", slot: "chest", ac: 18, weight: 60, value: 50000, description: "Heavy plate armor crafted from nearly indestructible adamantine." },
    { id: 'armor_dragon_red', name: "Red Dragon Scale Mail", type: "armor", rarity: "rare", slot: "chest", ac: 14, weight: 45, value: 45000, description: "Scale mail imbued with the essence of a red dragon, offering fire resistance." },
    { id: 'armor_dragon_blue', name: "Blue Dragon Scale Mail", type: "armor", rarity: "rare", slot: "chest", ac: 14, weight: 45, value: 45000, description: "Scale mail imbued with the essence of a blue dragon, offering lightning resistance." },
    { id: 'armor_elven', name: "Elven Chain", type: "armor", rarity: "rare", slot: "chest", ac: 14, weight: 20, value: 35000, description: "Chain mail so light and fine it can be worn under regular clothes." },
    { id: 'armor_demon', name: "Demon Armor", type: "armor", rarity: "rare", slot: "chest", ac: 17, weight: 65, value: 60000, description: "A cursed armor that grants great power but slowly corrupts its wearer." },
    { id: 'armor_invuln', name: "Armor of Invulnerability", type: "armor", rarity: "legendary", slot: "chest", ac: 18, weight: 65, value: 150000, description: "A legendary armor that grants its wearer near-total immunity to harm." },
    { id: 'shield_animated', name: "Animated Shield", type: "armor", rarity: "rare", slot: "offHand", ac: 3, weight: 6, value: 35000, description: "A shield that floats and defends its wielder without being held." },
    { id: 'shield_arrow', name: "Arrow-Catching Shield", type: "armor", rarity: "rare", slot: "offHand", ac: 3, weight: 6, value: 30000, description: "A magical shield that deflects incoming projectiles." },
    { id: 'shield_spell', name: "Spellguard Shield", type: "armor", rarity: "rare", slot: "offHand", ac: 2, weight: 6, value: 40000, description: "A shield that provides protection against magical effects." },
    { id: 'helm_brilliance', name: "Helm of Brilliance", type: "armor", rarity: "rare", slot: "head", ac: 1, weight: 3, value: 50000, description: "A gleaming helm that can shed bright light and cast powerful spells." },
    { id: 'helm_telepathy', name: "Helm of Telepathy", type: "armor", rarity: "uncommon", slot: "head", ac: 0, weight: 2, value: 12000, description: "A helm that grants the wearer limited telepathic abilities." },
    { id: 'helm_comprehend', name: "Helm of Comprehending Languages", type: "armor", rarity: "uncommon", slot: "head", ac: 0, weight: 2, value: 5000, description: "A simple helm that allows the wearer to understand any spoken language." },
    { id: 'boots_speed', name: "Boots of Speed", type: "armor", rarity: "rare", slot: "feet", ac: 0, weight: 1, value: 35000, description: "Magical boots that allow the wearer to move with incredible swiftness." },
    { id: 'boots_elven', name: "Boots of Elvenkind", type: "armor", rarity: "uncommon", slot: "feet", ac: 0, weight: 1, value: 8000, description: "Soft, supple boots that grant the wearer exceptional stealth." },
    { id: 'boots_striding', name: "Boots of Striding and Springing", type: "armor", rarity: "uncommon", slot: "feet", ac: 0, weight: 1, value: 6000, description: "These boots allow the wearer to leap and move with unnatural grace." },
    { id: 'boots_levitation', name: "Boots of Levitation", type: "armor", rarity: "rare", slot: "feet", ac: 0, weight: 1, value: 25000, description: "Magical boots that enable the wearer to float and fly." },
    { id: 'boots_flying', name: "Winged Boots", type: "armor", rarity: "rare", slot: "feet", ac: 0, weight: 1, value: 45000, description: "Boots adorned with feathers that grant the wearer the power of flight." },
    { id: 'gloves_missile', name: "Gloves of Missile Snaring", type: "armor", rarity: "uncommon", slot: "hands", ac: 0, weight: 0.5, value: 8000, description: "These gloves allow the wearer to snatch incoming projectiles from the air." },
    { id: 'gloves_thievery', name: "Gloves of Thievery", type: "armor", rarity: "uncommon", slot: "hands", ac: 0, weight: 0.5, value: 6000, description: "Fine leather gloves that enhance a rogue's nimble fingers." },
    { id: 'gauntlets_ogre', name: "Gauntlets of Ogre Power", type: "armor", rarity: "uncommon", slot: "hands", ac: 1, weight: 2, value: 15000, statsBonus: { str: 4 }, description: "Crude iron gauntlets that bestow the strength of an ogre." },
    { id: 'cloak_displacement', name: "Cloak of Displacement", type: "armor", rarity: "rare", slot: "cloak", ac: 0, weight: 1, value: 40000, description: "This cloak shimmers with an illusion that makes the wearer appear to be a few inches from their actual location." },
    { id: 'cloak_elven', name: "Cloak of Elvenkind", type: "armor", rarity: "uncommon", slot: "cloak", ac: 0, weight: 1, value: 8000, description: "A cloak woven with elven magic, granting its wearer superior stealth." },
    { id: 'cloak_protection', name: "Cloak of Protection", type: "armor", rarity: "uncommon", slot: "cloak", ac: 1, weight: 1, value: 15000, description: "A simple cloak imbued with protective magic." },
    { id: 'cloak_bat', name: "Cloak of the Bat", type: "armor", rarity: "rare", slot: "cloak", ac: 0, weight: 1, value: 35000, description: "A dark cloak that allows the wearer to transform into a bat or gain its senses." },
    { id: 'cloak_manta', name: "Cloak of the Manta Ray", type: "armor", rarity: "uncommon", slot: "cloak", ac: 0, weight: 1, value: 5000, description: "This cloak allows the wearer to swim with the speed and grace of a manta ray." },
 
    // === MAGICAL ACCESSORIES ===
    { id: 'ring_resist_fire', name: "Ring of Fire Resistance", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 20000, description: "A plain ring that grants its wearer resistance to fire damage." },
    { id: 'ring_resist_cold', name: "Ring of Cold Resistance", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 20000, description: "A plain ring that grants its wearer resistance to cold damage." },
    { id: 'ring_invisibility', name: "Ring of Invisibility", type: "accessory", rarity: "legendary", slot: "ring", weight: 0.1, value: 100000, description: "A legendary ring that can turn its wearer completely invisible." },
    { id: 'ring_spell_storing', name: "Ring of Spell Storing", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 45000, description: "A ring that can hold and cast spells stored within it." },
    { id: 'ring_regeneration', name: "Ring of Regeneration", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 55000, description: "A ring that slowly heals the wearer's wounds over time." },
    { id: 'ring_evasion', name: "Ring of Evasion", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 30000, description: "A ring that helps its wearer dodge attacks with incredible agility." },
    { id: 'ring_free_action', name: "Ring of Free Action", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 25000, description: "This ring prevents its wearer from being paralyzed or restrained." },
    { id: 'ring_telekinesis', name: "Ring of Telekinesis", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 50000, description: "A powerful ring that grants the ability to move objects with the mind." },
    { id: 'ring_x_ray', name: "Ring of X-Ray Vision", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 35000, description: "This ring allows the wearer to see through solid objects." },
    { id: 'ring_shooting_stars', name: "Ring of Shooting Stars", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 40000, description: "A ring that can conjure fiery projectiles like shooting stars." },
    { id: 'amulet_proof_loc', name: "Amulet of Proof Against Detection", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.2, value: 12000, description: "An amulet that shields the wearer from magical detection." },
    { id: 'amulet_planes', name: "Amulet of the Planes", type: "accessory", rarity: "rare", slot: "amulet", weight: 0.3, value: 75000, description: "A potent amulet that can transport its wearer to other planes of existence." },
    { id: 'periapt_health', name: "Periapt of Health", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.2, value: 8000, description: "A magical trinket that boosts the wearer's vitality." },
    { id: 'periapt_wound', name: "Periapt of Wound Closure", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.2, value: 12000, description: "This periapt accelerates natural healing and prevents bleeding out." },
    { id: 'scarab_protection', name: "Scarab of Protection", type: "accessory", rarity: "legendary", slot: "amulet", weight: 0.3, value: 100000, description: "A magical scarab that offers powerful defense against various forms of harm." },
    { id: 'brooch_shielding', name: "Brooch of Shielding", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.1, value: 10000, description: "A brooch that grants temporary magical protection." },
    { id: 'belt_giant_str', name: "Belt of Giant Strength", type: "accessory", rarity: "rare", slot: "belt", weight: 2, value: 50000, statsBonus: { str: 6 }, description: "A belt that imbues the wearer with colossal strength." },
    { id: 'belt_dwarvenkind', name: "Belt of Dwarvenkind", type: "accessory", rarity: "rare", slot: "belt", weight: 2, value: 35000, statsBonus: { con: 2 }, description: "A belt that grants the wearer some characteristics of a dwarf." },
    { id: 'headband_intellect', name: "Headband of Intellect", type: "accessory", rarity: "uncommon", slot: "head", weight: 0.2, value: 20000, statsBonus: { int: 4 }, description: "A simple headband that significantly boosts the wearer's intelligence." },
    { id: 'circlet_blasting', name: "Circlet of Blasting", type: "accessory", rarity: "uncommon", slot: "head", weight: 0.2, value: 15000, description: "A circlet that can emit powerful rays of force." },
    { id: 'ioun_fortitude', name: "Ioun Stone of Fortitude", type: "accessory", rarity: "rare", slot: "ring", weight: 0, value: 40000, statsBonus: { con: 2 }, description: "A magical stone that orbits the wearer's head, increasing their constitution." },
    { id: 'ioun_insight', name: "Ioun Stone of Insight", type: "accessory", rarity: "rare", slot: "ring", weight: 0, value: 40000, statsBonus: { wis: 2 }, description: "A magical stone that orbits the wearer's head, sharpening their wisdom." },
    { id: 'ioun_intellect', name: "Ioun Stone of Intellect", type: "accessory", rarity: "rare", slot: "ring", weight: 0, value: 40000, statsBonus: { int: 2 }, description: "A magical stone that orbits the wearer's head, boosting their intelligence." },
    { id: 'amulet_health', name: "Amulet of Health", type: "accessory", rarity: "rare", slot: "amulet", weight: 0.2, value: 25000, statsBonus: { con: 4 }, description: "This amulet fortifies the wearer's constitution, making them hardier." },

    // === POTIONS ===
    { id: 'antitoxin', name: "Antitoxin", type: "consumable", rarity: "common", value: 500, weight: 0.5, effect: { poison_cure: 1 }, description: "A milky fluid that neutralizes most common poisons." },
    { id: 'oil_slipperiness', name: "Oil of Slipperiness", type: "consumable", rarity: "uncommon", value: 2500, weight: 0.5, description: "A greasy oil that makes surfaces incredibly slippery." },
    { id: 'oil_sharpness', name: "Oil of Sharpness", type: "consumable", rarity: "rare", value: 8000, weight: 0.5, description: "An oil that, when applied to a weapon, makes its edge incredibly keen." },
    { id: 'pot_heal_greater', name: "Greater Healing Potion", type: "consumable", rarity: "uncommon", value: 1500, weight: 0.5, effect: { hp: 25 }, description: "A more potent healing potion." },
    { id: 'pot_heal_superior', name: "Superior Healing Potion", type: "consumable", rarity: "rare", value: 5000, weight: 0.5, effect: { hp: 50 }, description: "A powerful healing potion, used in dire situations." },
    { id: 'pot_heal_supreme', name: "Supreme Healing Potion", type: "consumable", rarity: "rare", value: 15000, weight: 0.5, effect: { hp: 100 }, description: "The most potent healing elixir, capable of closing grievous wounds." },
    { id: 'pot_mana', name: "Mana Potion", type: "consumable", rarity: "uncommon", value: 1000, weight: 0.5, effect: { mana: 15 }, description: "A shimmering blue potion that restores magical energy." },
    { id: 'pot_mana_greater', name: "Greater Mana Potion", type: "consumable", rarity: "rare", value: 3000, weight: 0.5, effect: { mana: 30 }, description: "A potent mana potion for experienced spellcasters." },
    { id: 'pot_stamina', name: "Stamina Potion", type: "consumable", rarity: "uncommon", value: 800, weight: 0.5, effect: { stamina: 15 }, description: "A green potion that revitalizes physical energy." },
    { id: 'pot_giant_str', name: "Potion of Giant Strength", type: "consumable", rarity: "rare", value: 8000, weight: 0.5, effect: { str_temp: 6 }, description: "Drinking this makes one feel as strong as a giant for a short time." },
    { id: 'pot_heroism', name: "Potion of Heroism", type: "consumable", rarity: "rare", value: 5000, weight: 0.5, effect: { temp_hp: 10 }, description: "A potion that fills the drinker with courage and temporary vitality." },
    { id: 'pot_speed', name: "Potion of Speed", type: "consumable", rarity: "rare", value: 8000, weight: 0.5, description: "This potion grants incredible swiftness, allowing for extra actions." },
    { id: 'pot_flying', name: "Potion of Flying", type: "consumable", rarity: "rare", value: 10000, weight: 0.5, description: "A light, effervescent potion that grants the ability to fly." },
    { id: 'pot_invisibility', name: "Potion of Invisibility", type: "consumable", rarity: "rare", value: 12000, weight: 0.5, description: "Drinking this potion turns the user invisible for a duration." },
    { id: 'pot_resistance_fire', name: "Potion of Fire Resistance", type: "consumable", rarity: "uncommon", value: 3000, weight: 0.5, description: "A potion that protects the drinker from fire." },
    { id: 'pot_resistance_cold', name: "Potion of Cold Resistance", type: "consumable", rarity: "uncommon", value: 3000, weight: 0.5, description: "A potion that protects the drinker from cold." },
    { id: 'pot_water_breathing', name: "Potion of Water Breathing", type: "consumable", rarity: "uncommon", value: 2000, weight: 0.5, description: "This potion allows the drinker to breathe underwater." },
    { id: 'pot_mind_reading', name: "Potion of Mind Reading", type: "consumable", rarity: "rare", value: 6000, weight: 0.5, description: "A rare potion that grants temporary telepathic abilities." },
    
    // === WONDROUS ITEMS ===
    { id: 'bag_holding', name: "Bag of Holding", type: "tool", rarity: "uncommon", weight: 0.5, value: 10000, description: "A seemingly ordinary bag that can hold an astonishing volume and weight of items." },
    { id: 'bag_tricks', name: "Bag of Tricks", type: "tool", rarity: "uncommon", weight: 0.5, value: 8000, description: "A small sack from which random animals can be pulled forth." },
    { id: 'portable_hole', name: "Portable Hole", type: "tool", rarity: "rare", weight: 0, value: 40000, description: "A disc of cloth that, when unfolded, creates a deep, extra-dimensional space." },
    { id: 'rope_climbing', name: "Rope of Climbing", type: "tool", rarity: "uncommon", weight: 3, value: 5000, description: "A magical rope that can tie itself, extend, and even climb on command." },
    { id: 'rope_entanglement', name: "Rope of Entanglement", type: "tool", rarity: "rare", weight: 3, value: 20000, description: "A rope that, when thrown, can grapple and entangle foes with vines." },
    { id: 'immovable_rod', name: "Immovable Rod", type: "tool", rarity: "uncommon", weight: 2, value: 8000, description: "A metal rod that, when a button is pressed, becomes magically fixed in place." },
    { id: 'decanter_water', name: "Decanter of Endless Water", type: "tool", rarity: "uncommon", weight: 2, value: 6000, description: "A stoppered flask that can produce fresh water on command." },
    { id: 'lantern_revealing', name: "Lantern of Revealing", type: "tool", rarity: "uncommon", weight: 2, value: 8000, description: "This lantern can shed light into the Ethereal Plane, revealing hidden things." },
    { id: 'eyes_eagle', name: "Eyes of the Eagle", type: "tool", rarity: "uncommon", weight: 0.1, value: 5000, description: "These lenses grant the wearer exceptionally keen eyesight." },
    { id: 'eyes_charming', name: "Eyes of Charming", type: "tool", rarity: "uncommon", weight: 0.1, value: 10000, description: "These lenses allow the wearer to magically charm others." },
    { id: 'goggles_night', name: "Goggles of Night", type: "tool", rarity: "uncommon", weight: 0.2, value: 5000, description: "These dark goggles grant the wearer perfect darkvision." },
    { id: 'gem_seeing', name: "Gem of Seeing", type: "tool", rarity: "rare", weight: 0.1, value: 35000, description: "A polished gem that, when looked through, grants true sight." },
    { id: 'gem_brightness', name: "Gem of Brightness", type: "tool", rarity: "uncommon", weight: 0.1, value: 6000, description: "A small gem that can emit bright light on command." },
    { id: 'crystal_ball', name: "Crystal Ball", type: "tool", rarity: "rare", weight: 3, value: 50000, description: "A scrying device that allows for distant magical observation." },
    { id: 'mirror_lifetrapping', name: "Mirror of Life Trapping", type: "tool", rarity: "rare", weight: 50, value: 60000, description: "A magical mirror that can trap creatures within its reflective surface." },
    { id: 'horn_blasting', name: "Horn of Blasting", type: "tool", rarity: "rare", weight: 2, value: 25000, description: "A mighty horn that, when blown, emits a destructive wave of force." },
    { id: 'horn_valhalla', name: "Horn of Valhalla", type: "tool", rarity: "rare", weight: 2, value: 35000, description: "A legendary horn that can summon spectral warriors from Valhalla." },
    { id: 'cube_force', name: "Cube of Force", type: "tool", rarity: "rare", weight: 0.5, value: 40000, description: "A small cube that can project an invisible wall of force around its wielder." },
    { id: 'bead_force', name: "Bead of Force", type: "consumable", rarity: "rare", value: 5000, weight: 0.1, description: "A small bead that explodes into a sphere of pure force upon impact." },
    { id: 'carpet_flying', name: "Carpet of Flying", type: "tool", rarity: "rare", weight: 15, value: 60000, description: "A magnificent rug that can carry passengers through the air." },
    { id: 'figurine_golem', name: "Figurine of Wondrous Power (Bronze Griffon)", type: "tool", rarity: "rare", weight: 0.5, value: 35000, description: "A bronze figurine that can transform into a living griffon for a short time." },
    { id: 'figurine_raven', name: "Figurine of Wondrous Power (Silver Raven)", type: "tool", rarity: "uncommon", weight: 0.3, value: 8000, description: "A silver figurine that can transform into a living raven, useful for scouting." },
    { id: 'necklace_fireballs', name: "Necklace of Fireballs", type: "tool", rarity: "rare", weight: 0.3, value: 30000, description: "A necklace adorned with magical beads, each capable of unleashing a fireball." },
    { id: 'necklace_adaptation', name: "Necklace of Adaptation", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.2, value: 12000, description: "This necklace allows the wearer to breathe in any environment." },
    { id: 'pearl_power', name: "Pearl of Power", type: "consumable", rarity: "uncommon", value: 8000, weight: 0.1, description: "A lustrous pearl that can restore one expended spell slot." },
    { id: 'sending_stones', name: "Sending Stones", type: "tool", rarity: "uncommon", weight: 0.5, value: 10000, description: "A pair of stones that allow for telepathic communication with each other across vast distances." },
    { id: 'spell_scroll_1', name: "Spell Scroll (Level 1)", type: "consumable", rarity: "common", value: 500, weight: 0.1, description: "A scroll containing a single 1st-level spell." },
    { id: 'spell_scroll_3', name: "Spell Scroll (Level 3)", type: "consumable", rarity: "uncommon", value: 2000, weight: 0.1, description: "A scroll containing a single 3rd-level spell." },
    { id: 'spell_scroll_5', name: "Spell Scroll (Level 5)", type: "consumable", rarity: "rare", value: 8000, weight: 0.1, description: "A scroll containing a single 5th-level spell." },
 
    // === LEGENDARY ARTIFACTS ===
    { id: 'book_vile', name: "Book of Vile Darkness", type: "tool", rarity: "legendary", weight: 5, value: 250000, description: "A dark tome of forbidden lore, capable of corrupting any who read it." },
    { id: 'book_exalted', name: "Book of Exalted Deeds", type: "tool", rarity: "legendary", weight: 5, value: 250000, description: "A sacred text filled with divine wisdom and goodness, capable of inspiring purity." },
    { id: 'eye_vecna', name: "Eye of Vecna", type: "accessory", rarity: "legendary", slot: "head", weight: 0, value: 500000, description: "The severed eye of the lich god Vecna, granting immense power at a terrible cost." },
    { id: 'hand_vecna', name: "Hand of Vecna", type: "accessory", rarity: "legendary", slot: "hands", weight: 1, value: 500000, description: "The severed hand of the lich god Vecna, bestowing unholy might at a terrible cost." },
    { id: 'orb_dragon', name: "Orb of Dragonkind", type: "tool", rarity: "legendary", weight: 3, value: 300000, description: "A powerful orb that grants control over dragons and can summon them." },
    { id: 'talisman_sphere', name: "Talisman of the Sphere", type: "accessory", rarity: "legendary", slot: "amulet", weight: 1, value: 400000, description: "A talisman that allows the wielder to control a Sphere of Annihilation." },
    { id: 'deck_many', name: "Deck of Many Things", type: "tool", rarity: "legendary", weight: 0.5, value: 1000000, description: "A fabled deck of cards, each with unpredictable and powerful magical effects." },
    { id: 'sphere_annihilation', name: "Sphere of Annihilation", type: "tool", rarity: "legendary", weight: 0, value: 750000, description: "A perfect sphere of absolute blackness, annihilating anything it touches." },
    { id: 'wand_wonder', name: "Wand of Wonder", type: "tool", rarity: "rare", weight: 1, value: 45000, description: "A magical wand with unpredictable and often humorous effects." },
    { id: 'wand_fireballs', name: "Wand of Fireballs", type: "tool", rarity: "rare", weight: 1, value: 50000, description: "A wand that can unleash devastating fireballs." },
    { id: 'wand_lightning', name: "Wand of Lightning Bolts", type: "tool", rarity: "rare", weight: 1, value: 50000, description: "A wand that can unleash searing bolts of lightning." },
    { id: 'wand_magic_missile', name: "Wand of Magic Missiles", type: "tool", rarity: "uncommon", weight: 1, value: 15000, description: "A simple wand that can cast the magic missile spell multiple times." },
    { id: 'wand_web', name: "Wand of Web", type: "tool", rarity: "uncommon", weight: 1, value: 12000, description: "A wand that can entangle foes in sticky, magical webs." },
    { id: 'wand_fear', name: "Wand of Fear", type: "tool", rarity: "rare", weight: 1, value: 35000, description: "A wand that can project a cone of paralyzing fear." },
    { id: 'wand_paralysis', name: "Wand of Paralysis", type: "tool", rarity: "rare", weight: 1, value: 40000, description: "A wand that can render foes immobile with a touch." },
    { id: 'rod_absorption', name: "Rod of Absorption", type: "tool", rarity: "rare", weight: 2, value: 60000, description: "A rod that can absorb incoming spells and store their energy." },
    { id: 'rod_lordly', name: "Rod of Lordly Might", type: "weapon", rarity: "legendary", slot: "mainHand", power: 8, weight: 5, value: 100000, description: "A legendary rod that can transform into various powerful weapons." },
    { id: 'rod_security', name: "Rod of Security", type: "tool", rarity: "rare", weight: 2, value: 45000, description: "A rod that can create a safe, extra-dimensional haven for its users." },
];
