import { Location } from '../types';

export const LOCATIONS_DB: Location[] = [
    // === Starting Areas ===
    { id: 'willowmere', name: "Willowmere Village", type: "town", description: "A peaceful farming village nestled in rolling hills, known for its warm hospitality and excellent ale.", connections: ['crossroads', 'whispering_woods', 'millbrook_farm'], npcs: ['elder_mira', 'blacksmith_thorn'], shopIds: ['general_store', 'tavern'], dangerLevel: 0, monsters: [] },
    { id: 'crossroads', name: "The Crossroads", type: "landmark", description: "A well-traveled intersection where four roads meet, marked by an ancient stone milestone.", connections: ['willowmere', 'ravenshollow', 'duskfall_ruins', 'merchant_pass', 'stormwatch_harbor'], monsters: ['goblin', 'kobold', 'wolf'], dangerLevel: 1 },
    { id: 'millbrook_farm', name: "Millbrook Farm", type: "landmark", description: "A prosperous farmstead with golden wheat fields and a creaking windmill.", connections: ['willowmere', 'whispering_woods'], monsters: ['rat', 'wolf'], dangerLevel: 1 },
 
    // === Wilderness ===
    { id: 'whispering_woods', name: "Whispering Woods", type: "wilderness", description: "An ancient forest where the trees seem to whisper secrets. Sunlight barely penetrates the dense canopy.", connections: ['willowmere', 'millbrook_farm', 'druid_grove', 'spider_hollow'], monsters: ['wolf', 'dire_wolf', 'giant_spider', 'owlbear'], dangerLevel: 3 },
    { id: 'spider_hollow', name: "Spider Hollow", type: "dungeon", description: "A web-choked ravine infested with giant spiders of all sizes.", connections: ['whispering_woods'], monsters: ['giant_spider'], dangerLevel: 4 },
    { id: 'druid_grove', name: "Druid's Grove", type: "temple", description: "A sacred clearing where druids commune with nature spirits around a moonlit pool.", connections: ['whispering_woods'], npcs: ['archdruid_oak'], shopIds: ['apothecary'], dangerLevel: 1, monsters: [] },
    { id: 'tideglass_cliffs', name: "Tideglass Cliffs", type: "wilderness", description: "Jagged sea cliffs glittering with mineral-veined stone, where harsh winds carry the scent of salt and kelp.", connections: ['stormwatch_harbor', 'saltwind_lighthouse', 'shipwreck_shoals'], monsters: ['reef_stalker', 'wolf'], dangerLevel: 3, encounters: ['coast_reef_stalker', 'coast_lighthouse_signal'] },
    { id: 'shipwreck_shoals', name: "Shipwreck Shoals", type: "wilderness", description: "Half-submerged wrecks and broken masts litter this treacherous shoreline, haunted by the drowned.", connections: ['tideglass_cliffs'], monsters: ['drowned_sailor'], dangerLevel: 4, encounters: ['coast_drowned_sailors'] },
    { id: 'merchant_pass', name: "Merchant's Pass", type: "wilderness", description: "A mountain road frequented by traders, though bandits lurk in the rocky outcrops.", connections: ['crossroads', 'ironhold', 'bandit_camp'], monsters: ['goblin', 'hobgoblin', 'bugbear'], dangerLevel: 3 },
    { id: 'bandit_camp', name: "Bandit Camp", type: "dungeon", description: "A hidden encampment where outlaws count their ill-gotten gains.", connections: ['merchant_pass'], monsters: ['hobgoblin', 'bugbear'], dangerLevel: 4 },
 
    // === Towns & Cities ===
    { id: 'ravenshollow', name: "Ravenshollow", type: "town", description: "A fog-shrouded town on the edge of cursed marshlands, its inhabitants wary of strangers.", connections: ['crossroads', 'marshes_of_sorrow', 'raven_manor'], npcs: ['mayor_corvus', 'witch_elara'], shopIds: ['apothecary', 'curiosities'], dangerLevel: 2, monsters: [] },
    { id: 'stormwatch_harbor', name: "Stormwatch Harbor", type: "town", description: "A bustling coastal town where storm-scarred ships dock beneath towering cliffs and ever-lit signal braziers.", connections: ['crossroads', 'tideglass_cliffs'], npcs: ['captain_maris', 'dockmaster_renn'], shopIds: ['dockside_outfitter'], dangerLevel: 1, monsters: [], encounters: ['coast_lighthouse_signal'] },
    { id: 'ironhold', name: "Ironhold Citadel", type: "castle", description: "A dwarven fortress carved into the mountainside, its forges burning day and night.", connections: ['merchant_pass', 'deep_mines', 'frozen_peaks'], npcs: ['king_thorin', 'forgemaster_brunhild'], shopIds: ['dwarven_armory', 'gem_merchant'], dangerLevel: 1, monsters: [] },
    { id: 'silverspire', name: "Silverspire City", type: "town", description: "The gleaming capital city, its towers reaching toward the heavens, center of magic and commerce.", connections: ['kings_road', 'mage_academy', 'noble_quarter'], npcs: ['archmage_vexis', 'queen_alara'], shopIds: ['grand_bazaar', 'enchanter', 'royal_armory'], dangerLevel: 0, monsters: [] },
    { id: 'kings_road', name: "King's Road", type: "landmark", description: "A well-maintained royal highway lined with waystones and patrol banners, connecting far-flung cities to the capital.", connections: ['silverspire', 'crossroads'], monsters: ['goblin', 'wolf'], dangerLevel: 2 },
    { id: 'noble_quarter', name: "Noble Quarter", type: "town", description: "A gated district of Silverspire where ornate villas and manicured gardens surround the city’s elite estates.", connections: ['silverspire'], npcs: ['queen_alara'], shopIds: ['grand_bazaar'], dangerLevel: 0, monsters: [] },
 
    // === Dungeons & Ruins ===
    { id: 'duskfall_ruins', name: "Duskfall Ruins", type: "ruin", description: "Crumbling remains of an ancient elven city, now home to the restless dead.", connections: ['crossroads', 'catacombs'], monsters: ['skeleton', 'zombie', 'ghost', 'wight'], dangerLevel: 4 },
    { id: 'catacombs', name: "The Catacombs", type: "dungeon", description: "Endless tunnels beneath Duskfall where the dead refuse to stay buried.", connections: ['duskfall_ruins', 'lich_sanctum'], monsters: ['skeleton', 'zombie', 'ghoul', 'ghast', 'wraith'], dangerLevel: 6 },
    { id: 'lich_sanctum', name: "Lich's Sanctum", type: "dungeon", description: "The hidden phylactery chamber of an ancient lich, pulsing with dark energy.", connections: ['catacombs'], monsters: ['lich', 'wraith', 'flameskull'], dangerLevel: 10 },
    { id: 'raven_manor', name: "Raven Manor", type: "dungeon", description: "A decrepit mansion where a vampire lord holds court over the damned.", connections: ['ravenshollow'], monsters: ['vampire_spawn', 'ghost', 'specter'], dangerLevel: 6 },
    { id: 'saltwind_lighthouse', name: "Saltwind Lighthouse", type: "dungeon", description: "An ancient lighthouse perched on storm-lashed cliffs, its beacon said to be haunted by lost sailors.", connections: ['tideglass_cliffs'], npcs: ['keeper_nessa'], monsters: ['drowned_sailor'], dangerLevel: 4, encounters: ['coast_lighthouse_signal', 'coast_drowned_sailors'] },
    { id: 'marshes_of_sorrow', name: "Marshes of Sorrow", type: "wilderness", description: "A fetid swamp where will-o-wisps lead travelers to watery graves.", connections: ['ravenshollow', 'hag_lair', 'lizardfolk_village'], monsters: ['zombie', 'ghoul', 'shadow'], dangerLevel: 5 },
    { id: 'hag_lair', name: "Hag's Lair", type: "dungeon", description: "A twisted hovel where a coven of hags brew terrible curses.", connections: ['marshes_of_sorrow'], monsters: ['harpy', 'ghast'], dangerLevel: 5 },
 
    // === Mountain & Underground ===
    { id: 'deep_mines', name: "Deep Mines", type: "dungeon", description: "Abandoned dwarven mines that delved too deep, awakening ancient horrors.", connections: ['ironhold', 'underdark_gate'], monsters: ['kobold', 'gargoyle', 'basilisk'], dangerLevel: 5 },
    { id: 'underdark_gate', name: "Underdark Gate", type: "dungeon", description: "A yawning portal to the lightless depths below, guarded by aberrations.", connections: ['deep_mines'], monsters: ['mind_flayer', 'beholder'], dangerLevel: 9 },
    { id: 'frozen_peaks', name: "Frozen Peaks", type: "wilderness", description: "Treacherous mountain summits where frost giants make their homes.", connections: ['ironhold', 'frost_giant_hold', 'dragon_eyrie'], monsters: ['wolf', 'dire_wolf', 'frost_giant'], dangerLevel: 7 },
    { id: 'frost_giant_hold', name: "Frost Giant Hold", type: "castle", description: "An ice fortress carved from a glacier, home to a frost giant jarl.", connections: ['frozen_peaks'], monsters: ['frost_giant', 'werewolf'], dangerLevel: 8 },
    { id: 'dragon_eyrie', name: "Dragon's Eyrie", type: "dungeon", description: "A mountain peak lair where an ancient dragon broods over its hoard.", connections: ['frozen_peaks'], monsters: ['adult_dragon_red', 'young_dragon_black'], dangerLevel: 10 },
 
    // === Special Locations ===
    { id: 'mage_academy', name: "Arcane Academy", type: "guild", description: "A floating tower where aspiring wizards learn the secrets of magic.", connections: ['silverspire'], npcs: ['archmage_vexis'], shopIds: ['enchanter', 'spell_components', 'scroll_shop'], dangerLevel: 0, monsters: [] },
    { id: 'temple_of_light', name: "Temple of the Dawn", type: "temple", description: "A grand cathedral dedicated to the sun god, its spires catching the first light of day.", connections: ['silverspire', 'celestial_sanctum'], npcs: [], dangerLevel: 0, monsters: [] },
    { id: 'celestial_sanctum', name: "Celestial Sanctum", type: "temple", description: "A hidden holy site where clerics commune with celestial beings.", connections: ['temple_of_light'], dangerLevel: 2, monsters: [] },
    { id: 'thieves_guild', name: "Shadow Market", type: "guild", description: "A secret underground bazaar where anything can be bought for the right price.", connections: ['silverspire'], npcs: ['guildmaster_shade'], shopIds: ['black_market', 'poison_vendor'], dangerLevel: 3, monsters: [] },
    { id: 'arena', name: "The Colosseum", type: "landmark", description: "A grand arena where warriors test their mettle against beasts and each other.", connections: ['silverspire'], npcs: ['arena_master'], monsters: ['ogre', 'troll', 'manticore'], dangerLevel: 4 },
    { id: 'plane_of_fire', name: "Plane of Fire", type: "dungeon", description: "A portal to the elemental plane of fire, where salamanders and efreet dwell.", connections: ['mage_academy'], monsters: ['salamander', 'fire_giant'], dangerLevel: 8 },
    { id: 'abyss_gate', name: "Abyssal Rift", type: "dungeon", description: "A tear in reality leading to the demonic Abyss, sealed by ancient wards.", connections: ['catacombs'], monsters: ['bone_devil', 'wraith'], dangerLevel: 10 },
    { id: 'lizardfolk_village', name: "Lizardfolk Village", type: "settlement", description: "A cluster of mud-and-reed huts built on stilts above the swamp. The lizardfolk here are wary of outsiders but open to trade.", connections: ['marshes_of_sorrow'], npcs: [], monsters: [], dangerLevel: 3 },

    // === NEW: Desert Region ===
    { id: 'sandstone_oasis', name: "Sandstone Oasis", type: "town", description: "A small trading post surrounding a spring in the desert. Palm trees and canvas awnings provide shade for weathered merchants.", connections: ['desert_road', 'sun_temple', 'scorpion_wastes'], npcs: [], shopIds: ['general_store'], dangerLevel: 1, monsters: [] },
    { id: 'desert_road', name: "Desert Road", type: "wilderness", description: "A sun-scorched trade route between distant cities. Mirages shimmer on the horizon and sand devils whirl across the dunes.", connections: ['sandstone_oasis', 'crossroads', 'nomad_encampment'], monsters: ['sand_crab', 'bandit'], dangerLevel: 3 },
    { id: 'scorpion_wastes', name: "Scorpion Wastes", type: "wilderness", description: "A barren expanse of cracked earth and bleached bones. Giant scorpions and sand worms lurk beneath the surface.", connections: ['sandstone_oasis', 'ancient_pyramid'], monsters: ['sand_crab', 'bulette', 'purple_worm'], dangerLevel: 6 },
    { id: 'ancient_pyramid', name: "Pyramid of the Sun King", type: "dungeon", description: "A colossal pyramid sealed for millennia, its traps still lethal and its guardians still vigilant.", connections: ['scorpion_wastes'], monsters: ['skeleton', 'animated_armor', 'helmed_horror', 'iron_golem'], dangerLevel: 8 },
    { id: 'sun_temple', name: "Temple of the Scorching Sun", type: "temple", description: "A golden-domed temple where fire priests tend eternal flames and offer blessings to desert travelers.", connections: ['sandstone_oasis'], npcs: [], dangerLevel: 1, monsters: [] },
    { id: 'nomad_encampment', name: "Nomad Encampment", type: "settlement", description: "A sprawl of colorful tents where desert nomads rest between journeys. They trade in rare spices and desert lore.", connections: ['desert_road'], npcs: [], dangerLevel: 1, monsters: [] },

    // === NEW: Coastal / Underwater ===
    { id: 'coral_reef_ruins', name: "Coral Reef Ruins", type: "dungeon", description: "Submerged elven ruins overgrown with living coral. Bioluminescent fish illuminate halls once walked by surface dwellers.", connections: ['shipwreck_shoals'], monsters: ['sahuagin', 'reef_stalker', 'reef_guardian', 'water_elemental'], dangerLevel: 5 },
    { id: 'pirates_cove', name: "Pirate's Cove", type: "settlement", description: "A hidden harbor carved into sea cliffs, home to smugglers, pirates, and those who ask no questions.", connections: ['stormwatch_harbor', 'tideglass_cliffs'], npcs: [], shopIds: ['black_market'], dangerLevel: 3, monsters: [] },
    { id: 'sea_serpent_strait', name: "Sea Serpent Strait", type: "wilderness", description: "A narrow channel between rocky islands where massive sea creatures hunt. Ships cross quickly or not at all.", connections: ['stormwatch_harbor', 'merfolk_grotto'], monsters: ['water_elemental', 'deepsea_stalker', 'kraken'], dangerLevel: 8 },
    { id: 'merfolk_grotto', name: "Merfolk Grotto", type: "settlement", description: "An underwater cavern city of the merfolk, accessible through a submerged tunnel. Air pockets allow surface-dwellers to breathe.", connections: ['sea_serpent_strait'], npcs: [], dangerLevel: 2, monsters: [] },

    // === NEW: Enchanted Forest ===
    { id: 'fey_crossing', name: "Fey Crossing", type: "landmark", description: "A shimmering portal between worlds where the Material Plane thins against the Feywild. Mushroom rings glow with otherworldly light.", connections: ['whispering_woods', 'feywild_glade'], monsters: ['quasit'], dangerLevel: 4 },
    { id: 'feywild_glade', name: "Feywild Glade", type: "wilderness", description: "A realm of impossible beauty — oversaturated colors, singing flowers, and time that flows like honey. Nothing is as it seems.", connections: ['fey_crossing', 'archfey_court'], monsters: ['displacer_beast', 'green_hag', 'phase_spider'], dangerLevel: 5 },
    { id: 'archfey_court', name: "Court of the Archfey", type: "castle", description: "A palace of living crystal and moonlight where the Archfey holds eternal revels. Mortals who linger may never return.", connections: ['feywild_glade'], npcs: [], dangerLevel: 7, monsters: [] },
    { id: 'blighted_grove', name: "Blighted Grove", type: "wilderness", description: "A corrupted section of forest where trees weep black sap and the ground squelches with rot. Something terrible happened here.", connections: ['whispering_woods'], monsters: ['twig_blight', 'needle_blight', 'shambling_mound', 'treant'], dangerLevel: 5 },

    // === NEW: Underdark Expansion ===
    { id: 'fungal_caverns', name: "Fungal Caverns", type: "dungeon", description: "Vast underground chambers carpeted with bioluminescent mushrooms the size of trees. Myconid colonies tend these gardens in silence.", connections: ['underdark_gate', 'drow_outpost'], monsters: ['violet_fungus', 'hook_horror', 'otyugh'], dangerLevel: 5 },
    { id: 'drow_outpost', name: "Drow Outpost", type: "settlement", description: "A dark elf military outpost carved from obsidian. Spider silk banners hang from stalactite towers.", connections: ['fungal_caverns', 'aboleth_lake'], monsters: ['drow', 'drider', 'phase_spider'], dangerLevel: 7 },
    { id: 'aboleth_lake', name: "Lake of Lost Memories", type: "dungeon", description: "A vast underground lake of perfectly still water. An aboleth lurks in its depths, hoarding the memories of civilizations long dead.", connections: ['drow_outpost'], monsters: ['aboleth', 'chuul', 'intellect_devourer'], dangerLevel: 9 },

    // === NEW: Volcanic / Fire Region ===
    { id: 'ember_wastes', name: "Ember Wastes", type: "wilderness", description: "A volcanic hellscape of lava rivers and ash storms. The air shimmers with heat and reeks of sulfur.", connections: ['plane_of_fire', 'obsidian_fortress'], monsters: ['fire_elemental', 'salamander', 'hell_hound'], dangerLevel: 7 },
    { id: 'obsidian_fortress', name: "Obsidian Fortress", type: "castle", description: "A fire giant stronghold built from volcanic glass. The forges within produce weapons of terrible power.", connections: ['ember_wastes'], monsters: ['fire_giant', 'iron_golem', 'helmed_horror'], dangerLevel: 9, encounters: [] },

    // === NEW: Celestial / Divine ===
    { id: 'astral_bridge', name: "Astral Bridge", type: "landmark", description: "A bridge of crystallized starlight spanning the void between planes. Travelers here may encounter beings of immense power.", connections: ['celestial_sanctum', 'abyss_gate'], monsters: ['solar', 'balor'], dangerLevel: 10 },

    // === NEW: Urban Expansion ===
    { id: 'sewers', name: "Silverspire Sewers", type: "dungeon", description: "A labyrinth of tunnels beneath the capital city. Thieves, cultists, and worse lurk in the fetid darkness.", connections: ['silverspire', 'thieves_guild'], monsters: ['rat', 'otyugh', 'gelatinous_cube', 'werewolf'], dangerLevel: 4 },
    { id: 'gladiator_pits', name: "Gladiator Pits", type: "dungeon", description: "Underground fighting rings beneath the Colosseum where illegal death matches draw wealthy spectators.", connections: ['arena'], monsters: ['minotaur', 'ettin', 'chimera'], dangerLevel: 6 },
    { id: 'clock_tower', name: "The Broken Clock Tower", type: "dungeon", description: "An abandoned clock tower in the old quarter where time moves strangely. Ghosts of clockworkers still tend its gears.", connections: ['silverspire'], monsters: ['ghost', 'animated_armor', 'flying_sword', 'helmed_horror'], dangerLevel: 5 },

    // === NEW: Northern Wastes ===
    { id: 'tundra_expanse', name: "Tundra Expanse", type: "wilderness", description: "An endless frozen plain where howling winds strip flesh from bone. Yetis and frost worms hunt across the white void.", connections: ['frozen_peaks', 'ice_tomb'], monsters: ['wolf', 'dire_wolf', 'abominable_yeti'], dangerLevel: 6 },
    { id: 'ice_tomb', name: "Tomb of the Frost Lich", type: "dungeon", description: "A frozen mausoleum entombed in ancient ice. A lich of terrible power sleeps within, guarded by frozen undead.", connections: ['tundra_expanse'], monsters: ['lich', 'wight', 'specter', 'wraith'], dangerLevel: 10 },
];
