import { Location } from '../types';

export const LOCATIONS_DB: Location[] = [
    // === Starting Areas ===
    { id: 'willowmere', name: "Willowmere Village", type: "town", description: "A peaceful farming village nestled in rolling hills, known for its warm hospitality and excellent ale.", connections: ['crossroads', 'whispering_woods', 'millbrook_farm'], npcs: ['elder_mira', 'blacksmith_thorn'], shopIds: ['general_store', 'tavern'], dangerLevel: 0, monsters: [] },
    { id: 'crossroads', name: "The Crossroads", type: "landmark", description: "A well-traveled intersection where four roads meet, marked by an ancient stone milestone.", connections: ['willowmere', 'ravenshollow', 'duskfall_ruins', 'merchant_pass', 'stormwatch_harbor'], monsters: ['goblin', 'kobold', 'wolf'], dangerLevel: 1 },
    { id: 'millbrook_farm', name: "Millbrook Farm", type: "landmark", description: "A prosperous farmstead with golden wheat fields and a creaking windmill.", connections: ['willowmere', 'whispering_woods'], monsters: ['rat', 'wolf'], dangerLevel: 1 },
 
    // === Wilderness ===
    { id: 'whispering_woods', name: "Whispering Woods", type: "wilderness", description: "An ancient forest where the trees seem to whisper secrets. Sunlight barely penetrates the dense canopy.", connections: ['willowmere', 'millbrook_farm', 'druid_grove', 'spider_hollow'], monsters: ['wolf', 'dire_wolf', 'giant_spider', 'owlbear'], dangerLevel: 3 },
    { id: 'spider_hollow', name: "Spider Hollow", type: "dungeon", description: "A web-choked ravine infested with giant spiders of all sizes.", connections: ['whispering_woods'], monsters: ['giant_spider'], dangerLevel: 4 },
    { id: 'druid_grove', name: "Druid's Grove", type: "temple", description: "A sacred clearing where druids commune with nature spirits around a moonlit pool.", connections: ['whispering_woods'], npcs: ['archdruid_oak'], shopIds: ['apothecary'], dangerLevel: 1, monsters: [] },
    { id: 'tideglass_cliffs', name: "Tideglass Cliffs", type: "wilderness", description: "Jagged sea cliffs glittering with mineral-veined stone, where harsh winds carry the scent of salt and kelp.", connections: ['stormwatch_harbor', 'saltwind_lighthouse', 'shipwreck_shoals', 'mistglass_cove'], monsters: ['reef_stalker', 'wolf'], dangerLevel: 3, encounters: ['coast_reef_stalker', 'coast_lighthouse_signal', 'coast_stormfront'] },
    { id: 'shipwreck_shoals', name: "Shipwreck Shoals", type: "wilderness", description: "Half-submerged wrecks and broken masts litter this treacherous shoreline, haunted by the drowned.", connections: ['tideglass_cliffs', 'sunken_grotto', 'smugglers_cove'], monsters: ['drowned_sailor', 'abyssal_eel'], dangerLevel: 4, encounters: ['coast_drowned_sailors', 'coast_salvage_cache'] },
    { id: 'mistglass_cove', name: "Mistglass Cove", type: "wilderness", description: "A sheltered inlet where the sea lies unnervingly still beneath pearly fog and shimmering tide pools.", connections: ['tideglass_cliffs', 'sunken_grotto', 'reefwatch_isle', 'smugglers_cove'], monsters: ['sand_crab', 'reef_serpent'], dangerLevel: 3, encounters: ['coast_crab_scavengers', 'coast_salvage_cache', 'coast_kelp_harvest'] },
    { id: 'reefwatch_isle', name: "Reefwatch Isle", type: "wilderness", description: "A low island crowned with wind-bent pines and watchtowers that spot pirate sails long before they reach shore.", connections: ['mistglass_cove', 'stormwatch_harbor', 'saltwind_lighthouse', 'reef_shrine'], monsters: ['pirate_raider', 'sahuagin'], dangerLevel: 3, encounters: ['coast_pirate_pressgang', 'coast_reef_serpent', 'coast_siren_song'] },
    { id: 'smugglers_cove', name: "Smuggler's Cove", type: "wilderness", description: "A hidden inlet masked by jagged rocks and fog, favored by smugglers and shadow traders.", connections: ['mistglass_cove', 'shipwreck_shoals', 'reefwatch_isle'], npcs: ['smuggler_broker_kess'], shopIds: ['smugglers_den'], monsters: ['smuggler_cutthroat', 'pirate_raider'], dangerLevel: 4, encounters: ['coast_smuggler_cache', 'coast_pirate_pressgang'] },
    { id: 'reef_shrine', name: "Reef Shrine", type: "temple", description: "A coral-ringed shrine where tide sages offer prayers to the sea's guardians.", connections: ['reefwatch_isle', 'sunken_grotto', 'sirens_vault'], npcs: ['tide_sage_oren', 'reef_priestess_lyra'], monsters: ['reef_guardian', 'tide_cultist'], dangerLevel: 4, encounters: ['coast_reef_ritual', 'coast_guardian_challenge'] },
    { id: 'merchant_pass', name: "Merchant's Pass", type: "wilderness", description: "A mountain road frequented by traders, though bandits lurk in the rocky outcrops.", connections: ['crossroads', 'ironhold', 'bandit_camp'], monsters: ['goblin', 'hobgoblin', 'bugbear'], dangerLevel: 3 },
    { id: 'bandit_camp', name: "Bandit Camp", type: "dungeon", description: "A hidden encampment where outlaws count their ill-gotten gains.", connections: ['merchant_pass'], monsters: ['hobgoblin', 'bugbear'], dangerLevel: 4 },
 
    // === Towns & Cities ===
    { id: 'ravenshollow', name: "Ravenshollow", type: "town", description: "A fog-shrouded town on the edge of cursed marshlands, its inhabitants wary of strangers.", connections: ['crossroads', 'marshes_of_sorrow', 'raven_manor'], npcs: ['mayor_corvus', 'witch_elara'], shopIds: ['apothecary', 'curiosities'], dangerLevel: 2, monsters: [] },
    { id: 'stormwatch_harbor', name: "Stormwatch Harbor", type: "town", description: "A bustling coastal town where storm-scarred ships dock beneath towering cliffs and ever-lit signal braziers.", connections: ['crossroads', 'tideglass_cliffs', 'stormwatch_docks', 'breakwater_market', 'reefwatch_isle'], npcs: ['captain_maris', 'dockmaster_renn', 'harbor_guard_captain'], shopIds: ['dockside_outfitter', 'harbor_services'], dangerLevel: 1, monsters: [], encounters: ['coast_lighthouse_signal', 'coast_stormwatch_patrol', 'coast_harbor_inspection'] },
    { id: 'stormwatch_docks', name: "Stormwatch Docks", type: "landmark", description: "Crowded piers lined with fishing skiffs, cargo cranes, and the constant smell of tar and salt.", connections: ['stormwatch_harbor', 'breakwater_market', 'shipwrights_yard'], npcs: ['dockmaster_renn', 'salvager_brine', 'salvage_master_ivo'], shopIds: ['dockside_outfitter', 'salvagers_coop'], dangerLevel: 1, monsters: [], encounters: ['coast_shipwright_request', 'coast_salvage_contract'] },
    { id: 'breakwater_market', name: "Breakwater Market", type: "town", description: "A lively bazaar sheltered behind stone breakwaters, where sailors trade tales and exotic cargo.", connections: ['stormwatch_harbor', 'stormwatch_docks'], npcs: ['market_factor_seren'], shopIds: ['breakwater_stalls', 'tideglass_curios'], dangerLevel: 0, monsters: [] },
    { id: 'shipwrights_yard', name: "Shipwright's Yard", type: "landmark", description: "Dry docks and half-built hulls dominate this yard, the air thick with sawdust and pitch.", connections: ['stormwatch_docks', 'stormwatch_harbor'], npcs: ['master_shipwright_arden'], shopIds: ['shipwrights_guild'], dangerLevel: 0, monsters: [], encounters: ['coast_hull_repair'] },
    { id: 'ironhold', name: "Ironhold Citadel", type: "castle", description: "A dwarven fortress carved into the mountainside, its forges burning day and night.", connections: ['merchant_pass', 'deep_mines', 'frozen_peaks'], npcs: ['king_thorin', 'blacksmith_thorn'], shopIds: ['dwarven_armory', 'gem_merchant'], dangerLevel: 1, monsters: [] },
    { id: 'silverspire', name: "Silverspire City", type: "town", description: "The gleaming capital city, its towers reaching toward the heavens, center of magic and commerce.", connections: ['kings_road', 'mage_academy', 'noble_quarter'], npcs: ['archmage_vexis', 'queen_alara'], shopIds: ['grand_bazaar', 'enchanter', 'royal_armory'], dangerLevel: 0, monsters: [] },
    { id: 'kings_road', name: "King's Road", type: "landmark", description: "A well-maintained royal highway lined with waystones and patrol banners, connecting far-flung cities to the capital.", connections: ['silverspire', 'crossroads'], monsters: ['goblin', 'wolf'], dangerLevel: 2 },
    { id: 'noble_quarter', name: "Noble Quarter", type: "town", description: "A gated district of Silverspire where ornate villas and manicured gardens surround the city’s elite estates.", connections: ['silverspire'], npcs: ['queen_alara'], shopIds: ['grand_bazaar'], dangerLevel: 0, monsters: [] },
 
    // === Dungeons & Ruins ===
    { id: 'duskfall_ruins', name: "Duskfall Ruins", type: "ruin", description: "Crumbling remains of an ancient elven city, now home to the restless dead.", connections: ['crossroads', 'catacombs'], monsters: ['skeleton', 'zombie', 'ghost', 'wight'], dangerLevel: 4 },
    { id: 'catacombs', name: "The Catacombs", type: "dungeon", description: "Endless tunnels beneath Duskfall where the dead refuse to stay buried.", connections: ['duskfall_ruins', 'lich_sanctum'], monsters: ['skeleton', 'zombie', 'ghoul', 'ghast', 'wraith'], dangerLevel: 6 },
    { id: 'lich_sanctum', name: "Lich's Sanctum", type: "dungeon", description: "The hidden phylactery chamber of an ancient lich, pulsing with dark energy.", connections: ['catacombs'], monsters: ['lich', 'wraith', 'flameskull'], dangerLevel: 10 },
    { id: 'raven_manor', name: "Raven Manor", type: "dungeon", description: "A decrepit mansion where a vampire lord holds court over the damned.", connections: ['ravenshollow'], monsters: ['vampire_spawn', 'ghost', 'specter'], dangerLevel: 6 },
    { id: 'saltwind_lighthouse', name: "Saltwind Lighthouse", type: "dungeon", description: "An ancient lighthouse perched on storm-lashed cliffs, its beacon said to be haunted by lost sailors.", connections: ['tideglass_cliffs', 'reefwatch_isle', 'saltspire_depths'], npcs: ['keeper_nessa'], monsters: ['drowned_sailor', 'brinebound_knight'], dangerLevel: 4, encounters: ['coast_lighthouse_signal', 'coast_drowned_sailors', 'coast_brinebound_duel'] },
    { id: 'sunken_grotto', name: "Sunken Grotto", type: "dungeon", description: "A brine-filled cavern accessible at low tide, where shipwreck treasures glint beneath kelp-choked waters.", connections: ['shipwreck_shoals', 'mistglass_cove', 'reef_shrine', 'abyssal_trench'], monsters: ['kelp_wraith', 'reef_serpent', 'abyssal_eel'], dangerLevel: 5, encounters: ['coast_kelp_wraith', 'coast_salvage_cache', 'coast_abyssal_maw'] },
    { id: 'saltspire_depths', name: "Saltspire Depths", type: "dungeon", description: "A flooded stairwell beneath the lighthouse that leads to forgotten tide chambers.", connections: ['saltwind_lighthouse'], monsters: ['brinebound_knight', 'tide_cultist'], dangerLevel: 5, encounters: ['coast_brinebound_duel', 'coast_tide_omen'] },
    { id: 'sirens_vault', name: "Siren's Vault", type: "dungeon", description: "A reef-carved vault that echoes with distant song and glimmering relics.", connections: ['reef_shrine', 'abyssal_trench'], monsters: ['storm_siren', 'reef_guardian'], dangerLevel: 6, encounters: ['coast_siren_song', 'coast_vault_relic'] },
    { id: 'abyssal_trench', name: "Abyssal Trench", type: "dungeon", description: "A yawning drop into the darkest waters, home to ancient horrors and lost treasure.", connections: ['sunken_grotto', 'sirens_vault'], monsters: ['deepsea_stalker', 'abyssal_eel'], dangerLevel: 7, encounters: ['coast_abyssal_maw', 'coast_deepsea_hunt'] },
    { id: 'marshes_of_sorrow', name: "Marshes of Sorrow", type: "wilderness", description: "A fetid swamp where will-o-wisps lead travelers to watery graves.", connections: ['ravenshollow', 'hag_lair', 'lizardfolk_village'], monsters: ['zombie', 'ghoul', 'shadow'], dangerLevel: 5 },
    { id: 'hag_lair', name: "Hag's Lair", type: "dungeon", description: "A twisted hovel where a coven of hags brew terrible curses.", connections: ['marshes_of_sorrow'], monsters: ['harpy', 'ghast'], dangerLevel: 5 },
 
    // === Mountain & Underground ===
    { id: 'deep_mines', name: "Deep Mines", type: "dungeon", description: "Abandoned dwarven mines that delved too deep, awakening ancient horrors.", connections: ['ironhold', 'underdark_gate'], monsters: ['kobold', 'gargoyle', 'basilisk'], dangerLevel: 5 },
    { id: 'underdark_gate', name: "Underdark Gate", type: "dungeon", description: "A yawning portal to the lightless depths below, guarded by aberrations.", connections: ['deep_mines'], monsters: ['mind_flayer', 'beholder'], dangerLevel: 9 },
    { id: 'frozen_peaks', name: "Frozen Peaks", type: "wilderness", description: "Treacherous mountain summits where frost giants make their homes.", connections: ['ironhold', 'frost_giant_hold', 'dragon_eyrie'], monsters: ['wolf', 'dire_wolf', 'frost_giant'], dangerLevel: 7 },
    { id: 'frost_giant_hold', name: "Frost Giant Hold", type: "castle", description: "An ice fortress carved from a glacier, home to a frost giant jarl.", connections: ['frozen_peaks'], monsters: ['frost_giant', 'werewolf'], dangerLevel: 8 },
    { id: 'dragon_eyrie', name: "Dragon's Eyrie", type: "dungeon", description: "A mountain peak lair where an ancient dragon broods over its hoard.", connections: ['frozen_peaks'], monsters: ['adult_dragon_red', 'young_dragon_black'], dangerLevel: 10 },
 
    // === Special Locations ===
    { id: 'mage_academy', name: "Arcane Academy", type: "guild", description: "A floating tower where aspiring wizards learn the secrets of magic.", connections: ['silverspire'], npcs: ['archmage_vexis'], shopIds: ['enchanter', 'spell_components', 'scroll_shop'], dangerLevel: 0, monsters: [] },
    { id: 'temple_of_light', name: "Temple of the Dawn", type: "temple", description: "A grand cathedral dedicated to the sun god, its spires catching the first light of day.", connections: ['silverspire', 'celestial_sanctum'], npcs: [], dangerLevel: 0, monsters: [] },
    { id: 'celestial_sanctum', name: "Celestial Sanctum", type: "temple", description: "A hidden holy site where clerics commune with celestial beings.", connections: ['temple_of_light'], dangerLevel: 2, monsters: [] },
    { id: 'thieves_guild', name: "Shadow Market", type: "guild", description: "A secret underground bazaar where anything can be bought for the right price.", connections: ['silverspire'], npcs: ['guildmaster_shade'], shopIds: ['black_market', 'poison_vendor'], dangerLevel: 3, monsters: [] },
    { id: 'arena', name: "The Colosseum", type: "landmark", description: "A grand arena where warriors test their mettle against beasts and each other.", connections: ['silverspire'], npcs: ['arena_master'], monsters: ['ogre', 'troll', 'manticore'], dangerLevel: 4 },
    { id: 'plane_of_fire', name: "Plane of Fire", type: "dungeon", description: "A portal to the elemental plane of fire, where salamanders and efreet dwell.", connections: ['mage_academy'], monsters: ['salamander', 'fire_giant'], dangerLevel: 8 },
    { id: 'abyss_gate', name: "Abyssal Rift", type: "dungeon", description: "A tear in reality leading to the demonic Abyss, sealed by ancient wards.", connections: ['catacombs'], monsters: ['bone_devil', 'wraith'], dangerLevel: 10 },
];
