import { RaceData } from '../types';

export const RACES: { [key: string]: RaceData } = {
  "Human": { traits: ["Versatile", "Ambitious"], speed: 30, bonus: { all: 1 }, startingLocation: "Crossroads Village" },
  "Elf": { subraces: ["High", "Wood", "Drow", "Eladrin", "Shadar-kai", "Sea", "Astral"], traits: ["Darkvision", "Keen Senses"], speed: 30, startingLocation: "Elven Glade" },
  "Dwarf": { subraces: ["Hill", "Mountain", "Duergar"], traits: ["Darkvision", "Resilience"], speed: 25, startingLocation: "Mountain Hold" },
  "Halfling": { subraces: ["Lightfoot", "Stout"], traits: ["Lucky", "Brave"], speed: 25, startingLocation: "Shire Hamlet" },
  "Gnome": { subraces: ["Forest", "Rock", "Deep"], traits: ["Cunning"], speed: 25, startingLocation: "Gnomish Workshop" },
  "Dragonborn": { subraces: ["Chromatic", "Metallic", "Gem"], traits: ["Breath Weapon"], speed: 30, startingLocation: "Draconic Outpost" },
  "Tiefling": { traits: ["Darkvision", "Hellish Resistance"], speed: 30, startingLocation: "Port City Slums" },
  "Half-Orc": { traits: ["Relentless Endurance"], speed: 30, startingLocation: "Wilderlands Camp" },
  "Half-Elf": { traits: ["Fey Ancestry"], speed: 30, startingLocation: "Border Town" },
  "Aarakocra": { traits: ["Flight"], speed: 25 }, "Aasimar": { traits: ["Healing Hands", "Light Bearer"], speed: 30 }, "Bugbear": { traits: ["Long Limbed", "Sneaky"], speed: 30 }, "Centaur": { traits: ["Charge", "Equine Build"], speed: 40 }, "Changeling": { traits: ["Shapechanger"], speed: 30 }, "Dhampir": { traits: ["Spider Climb", "Vampiric Bite"], speed: 35 }, "Fairy": { traits: ["Flight", "Fey Magic"], speed: 30 }, "Firbolg": { traits: ["Hidden Step", "Speech of Beast"], speed: 30 }, "Genasi": { subraces: ["Air", "Earth", "Fire", "Water"], traits: ["Elemental Legacy"], speed: 30 }, "Gith": { subraces: ["Githyanki", "Githzerai"], traits: ["Psionics"], speed: 30 }, "Goblin": { traits: ["Nimble Escape"], speed: 30 }, "Goliath": { traits: ["Stone's Endurance"], speed: 30 }, "Harengon": { traits: ["Rabbit Hop", "Lucky Footwork"], speed: 30 }, "Kenku": { traits: ["Mimicry"], speed: 30 }, "Kobold": { traits: ["Pack Tactics"], speed: 30 }, "Leonin": { traits: ["Daunting Roar"], speed: 35 }, "Lizardfolk": { traits: ["Natural Armor", "Bite"], speed: 30 }, "Minotaur": { traits: ["Horns", "Hammering Horns"], speed: 30 }, "Orc": { traits: ["Adrenaline Rush"], speed: 30 }, "Satyr": { traits: ["Magic Resistance", "Mirthful Leaps"], speed: 35 }, "Shifter": { traits: ["Shifting"], speed: 30 }, "Tabaxi": { traits: ["Feline Agility", "Claws"], speed: 30 }, "Tortle": { traits: ["Natural Armor", "Shell Defense"], speed: 30 }, "Triton": { traits: ["Amphibious", "Control Air/Water"], speed: 30 }, "Warforged": { traits: ["Constructed Resilience", "Integrated Protection"], speed: 30 }, "Yuan-Ti": { traits: ["Magic Resistance", "Poison Immunity"], speed: 30 }, "Autognome": { traits: ["Built for Success"], speed: 30 }, "Giff": { traits: ["Firearms Knowledge"], speed: 30 }, "Hadozee": { traits: ["Glide"], speed: 30 }, "Locathah": { traits: ["Leviathan Will"], speed: 30 }, "Owlin": { traits: ["Silent Flight"], speed: 30 }, "Plasmoid": { traits: ["Amorphous"], speed: 30 }, "Reborn": { traits: ["Deathless Nature"], speed: 30 }, "Thri-kreen": { traits: ["Chameleon Carapace"], speed: 30 }, "Verdan": { traits: ["Telepathic Insight"], speed: 30 }
};