import { Spell } from '../types';

export const SPELLS_DB: Spell[] = [ 
    // === CANTRIPS (Cost: 1-2) ===
    { id: 'firebolt', name: "Fire Bolt", cost: 2, damage: 8, school: "Evocation", target: "enemy", description: "A mote of fire hurled at a foe." },
    { id: 'ray_frost', name: "Ray of Frost", cost: 2, damage: 6, school: "Evocation", target: "enemy" },
    { id: 'shocking_grasp', name: "Shocking Grasp", cost: 2, damage: 7, school: "Evocation", target: "enemy" },
    { id: 'eldritch_blast', name: "Eldritch Blast", cost: 2, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'sacred_flame', name: "Sacred Flame", cost: 2, damage: 6, school: "Evocation", target: "enemy" },
    { id: 'toll_the_dead', name: "Toll the Dead", cost: 2, damage: 8, school: "Necromancy", target: "enemy" },
    { id: 'chill_touch', name: "Chill Touch", cost: 2, damage: 6, school: "Necromancy", target: "enemy" },
    { id: 'acid_splash', name: "Acid Splash", cost: 2, damage: 5, school: "Conjuration", target: "enemy" },
    { id: 'poison_spray', name: "Poison Spray", cost: 2, damage: 10, school: "Conjuration", target: "enemy" },
    { id: 'produce_flame', name: "Produce Flame", cost: 1, damage: 6, school: "Conjuration", target: "enemy" },
    { id: 'light', name: "Light", cost: 1, buff: "Illuminated", duration: 10, school: "Evocation", target: "self" },
    { id: 'mage_hand', name: "Mage Hand", cost: 1, buff: "Spectral Hand", duration: 5, school: "Conjuration", target: "self" },
    { id: 'prestidigitation', name: "Prestidigitation", cost: 1, buff: "Minor Magic", duration: 3, school: "Transmutation", target: "self" },
    { id: 'minor_illusion', name: "Minor Illusion", cost: 1, buff: "Illusory Distraction", duration: 3, school: "Illusion", target: "self" },
    { id: 'guidance', name: "Guidance", cost: 1, buff: "Guided", duration: 1, school: "Divination", target: "ally" },
    { id: 'resistance', name: "Resistance", cost: 1, buff: "Resistant", duration: 1, school: "Abjuration", target: "ally" },
    { id: 'thaumaturgy', name: "Thaumaturgy", cost: 1, buff: "Intimidating Presence", duration: 2, school: "Transmutation", target: "self" },
    { id: 'druidcraft', name: "Druidcraft", cost: 1, buff: "Nature's Touch", duration: 3, school: "Transmutation", target: "self" },
    { id: 'spare_dying', name: "Spare the Dying", cost: 1, heal: 1, school: "Necromancy", target: "ally" },
    { id: 'blade_ward', name: "Blade Ward", cost: 1, buff: "Warded", duration: 1, school: "Abjuration", target: "self" },
 
    // === LEVEL 1 SPELLS (Cost: 3-5) ===
    { id: 'heal', name: "Cure Wounds", cost: 5, heal: 12, school: "Evocation", target: "ally" },
    { id: 'healing_word', name: "Healing Word", cost: 3, heal: 8, school: "Evocation", target: "ally" },
    { id: 'goodberry', name: "Goodberry", cost: 3, heal: 10, school: "Transmutation", target: "ally" },
    { id: 'shield', name: "Shield", cost: 3, buff: "Shielded", duration: 2, school: "Abjuration", target: "self" },
    { id: 'mage_armor', name: "Mage Armor", cost: 4, buff: "Mage Armor", duration: 8, school: "Abjuration", target: "self" },
    { id: 'sanctuary', name: "Sanctuary", cost: 3, buff: "Sanctuary", duration: 3, school: "Abjuration", target: "ally" },
    { id: 'shield_faith', name: "Shield of Faith", cost: 3, buff: "Faith Shield", duration: 5, school: "Abjuration", target: "ally" },
    { id: 'absorb_elements', name: "Absorb Elements", cost: 3, buff: "Elemental Absorption", duration: 1, school: "Abjuration", target: "self" },
    { id: 'magic_missile', name: "Magic Missile", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'burning_hands', name: "Burning Hands", cost: 4, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'thunderwave', name: "Thunderwave", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'chromatic_orb', name: "Chromatic Orb", cost: 5, damage: 14, school: "Evocation", target: "enemy" },
    { id: 'ice_knife', name: "Ice Knife", cost: 4, damage: 12, school: "Conjuration", target: "enemy" },
    { id: 'inflict_wounds', name: "Inflict Wounds", cost: 5, damage: 16, school: "Necromancy", target: "enemy" },
    { id: 'guiding_bolt', name: "Guiding Bolt", cost: 4, damage: 14, school: "Evocation", target: "enemy" },
    { id: 'hellish_rebuke', name: "Hellish Rebuke", cost: 4, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'witchbolt', name: "Witch Bolt", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'earth_tremor', name: "Earth Tremor", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'sleep', name: "Sleep", cost: 4, buff: "Sleep Aura", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'charm_person', name: "Charm Person", cost: 4, buff: "Charmed", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'command', name: "Command", cost: 3, buff: "Commanded", duration: 1, school: "Enchantment", target: "enemy" },
    { id: 'bane', name: "Bane", cost: 4, buff: "Baned", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'bless', name: "Bless", cost: 4, buff: "Blessed", duration: 5, school: "Enchantment", target: "ally" },
    { id: 'heroism', name: "Heroism", cost: 4, buff: "Heroic", duration: 5, school: "Enchantment", target: "ally" },
    { id: 'faerie_fire', name: "Faerie Fire", cost: 4, buff: "Revealed", duration: 3, school: "Evocation", target: "enemy" },
    { id: 'entangle', name: "Entangle", cost: 4, buff: "Entangled", duration: 3, school: "Conjuration", target: "enemy" },
    { id: 'fog_cloud', name: "Fog Cloud", cost: 3, buff: "Obscured", duration: 5, school: "Conjuration", target: "self" },
    { id: 'grease', name: "Grease", cost: 3, buff: "Slippery Ground", duration: 3, school: "Conjuration", target: "enemy" },
    { id: 'disguise_self', name: "Disguise Self", cost: 3, buff: "Disguised", duration: 10, school: "Illusion", target: "self" },
    { id: 'silent_image', name: "Silent Image", cost: 3, buff: "Illusory Cover", duration: 5, school: "Illusion", target: "self" },
    { id: 'detect_magic', name: "Detect Magic", cost: 3, buff: "Magic Sight", duration: 5, school: "Divination", target: "self" },
    { id: 'identify', name: "Identify", cost: 3, buff: "Identified", duration: 1, school: "Divination", target: "self" },
    { id: 'hunters_mark', name: "Hunter's Mark", cost: 3, buff: "Marked Prey", duration: 10, school: "Divination", target: "enemy" },
    { id: 'hex', name: "Hex", cost: 3, damage: 4, school: "Enchantment", target: "enemy" },
    { id: 'false_life', name: "False Life", cost: 3, heal: 8, school: "Necromancy", target: "self" },
    { id: 'expeditious_retreat', name: "Expeditious Retreat", cost: 3, buff: "Hastened", duration: 5, school: "Transmutation", target: "self" },
    { id: 'jump', name: "Jump", cost: 3, buff: "Enhanced Leap", duration: 3, school: "Transmutation", target: "self" },
    { id: 'longstrider', name: "Longstrider", cost: 3, buff: "Swift", duration: 10, school: "Transmutation", target: "self" },
    { id: 'feather_fall', name: "Feather Fall", cost: 3, buff: "Featherweight", duration: 1, school: "Transmutation", target: "ally" },
 
    // === LEVEL 2 SPELLS (Cost: 6-8) ===
    { id: 'prayer_healing', name: "Prayer of Healing", cost: 8, heal: 18, school: "Evocation", target: "ally" },
    { id: 'lesser_restoration', name: "Lesser Restoration", cost: 6, heal: 5, school: "Abjuration", target: "ally" },
    { id: 'aid', name: "Aid", cost: 6, heal: 10, school: "Abjuration", target: "ally" },
    { id: 'scorching_ray', name: "Scorching Ray", cost: 7, damage: 18, school: "Evocation", target: "enemy" },
    { id: 'shatter', name: "Shatter", cost: 7, damage: 16, school: "Evocation", target: "enemy" },
    { id: 'melfs_acid_arrow', name: "Melf's Acid Arrow", cost: 7, damage: 16, school: "Evocation", target: "enemy" },
    { id: 'spiritual_weapon', name: "Spiritual Weapon", cost: 6, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'moonbeam', name: "Moonbeam", cost: 7, damage: 14, school: "Evocation", target: "enemy" },
    { id: 'flame_blade', name: "Flame Blade", cost: 6, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'cloud_daggers', name: "Cloud of Daggers", cost: 6, damage: 14, school: "Conjuration", target: "enemy" },
    { id: 'ray_enfeeblement', name: "Ray of Enfeeblement", cost: 6, damage: 8, school: "Necromancy", target: "enemy" },
    { id: 'blindness', name: "Blindness/Deafness", cost: 6, buff: "Blinded", duration: 3, school: "Necromancy", target: "enemy" },
    { id: 'mirror_image', name: "Mirror Image", cost: 6, buff: "Mirror Images", duration: 5, school: "Illusion", target: "self" },
    { id: 'invisibility', name: "Invisibility", cost: 7, buff: "Invisible", duration: 5, school: "Illusion", target: "ally" },
    { id: 'blur', name: "Blur", cost: 6, buff: "Blurred", duration: 5, school: "Illusion", target: "self" },
    { id: 'misty_step', name: "Misty Step", cost: 6, buff: "Teleported", duration: 1, school: "Conjuration", target: "self" },
    { id: 'hold_person', name: "Hold Person", cost: 7, buff: "Paralyzed", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'crown_madness', name: "Crown of Madness", cost: 6, buff: "Maddened", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'suggestion', name: "Suggestion", cost: 7, buff: "Suggested", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'calm_emotions', name: "Calm Emotions", cost: 6, buff: "Calmed", duration: 3, school: "Enchantment", target: "ally" },
    { id: 'web', name: "Web", cost: 6, buff: "Webbed", duration: 5, school: "Conjuration", target: "enemy" },
    { id: 'spike_growth', name: "Spike Growth", cost: 7, damage: 10, school: "Transmutation", target: "enemy" },
    { id: 'barkskin', name: "Barkskin", cost: 6, buff: "Barkskin", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'enlarge_reduce', name: "Enlarge/Reduce", cost: 6, buff: "Enlarged", duration: 5, school: "Transmutation", target: "ally" },
    { id: 'heat_metal', name: "Heat Metal", cost: 7, damage: 12, school: "Transmutation", target: "enemy" },
    { id: 'see_invisibility', name: "See Invisibility", cost: 6, buff: "True Sight", duration: 10, school: "Divination", target: "self" },
    { id: 'detect_thoughts', name: "Detect Thoughts", cost: 6, buff: "Mind Reading", duration: 5, school: "Divination", target: "self" },
    { id: 'darkness', name: "Darkness", cost: 6, buff: "Magical Darkness", duration: 5, school: "Evocation", target: "self" },
    { id: 'warding_bond', name: "Warding Bond", cost: 7, buff: "Bonded Protection", duration: 10, school: "Abjuration", target: "ally" },
 
    // === LEVEL 3 SPELLS (Cost: 9-12) ===
    { id: 'fireball', name: "Fireball", cost: 10, damage: 28, school: "Evocation", target: "enemy" },
    { id: 'lightning_bolt', name: "Lightning Bolt", cost: 10, damage: 28, school: "Evocation", target: "enemy" },
    { id: 'call_lightning', name: "Call Lightning", cost: 10, damage: 24, school: "Conjuration", target: "enemy" },
    { id: 'spirit_guardians', name: "Spirit Guardians", cost: 10, damage: 20, school: "Conjuration", target: "enemy" },
    { id: 'vampiric_touch', name: "Vampiric Touch", cost: 10, damage: 18, school: "Necromancy", target: "enemy" },
    { id: 'hunger_hadar', name: "Hunger of Hadar", cost: 10, damage: 16, school: "Conjuration", target: "enemy" },
    { id: 'erupting_earth', name: "Erupting Earth", cost: 9, damage: 20, school: "Transmutation", target: "enemy" },
    { id: 'tidal_wave', name: "Tidal Wave", cost: 9, damage: 18, school: "Conjuration", target: "enemy" },
    { id: 'mass_healing_word', name: "Mass Healing Word", cost: 10, heal: 15, school: "Evocation", target: "ally" },
    { id: 'revivify', name: "Revivify", cost: 12, heal: 30, school: "Necromancy", target: "ally" },
    { id: 'beacon_hope', name: "Beacon of Hope", cost: 9, buff: "Hopeful", duration: 5, school: "Abjuration", target: "ally" },
    { id: 'counterspell', name: "Counterspell", cost: 9, buff: "Spell Negated", duration: 1, school: "Abjuration", target: "enemy" },
    { id: 'dispel_magic', name: "Dispel Magic", cost: 9, buff: "Dispelled", duration: 1, school: "Abjuration", target: "enemy" },
    { id: 'remove_curse', name: "Remove Curse", cost: 9, heal: 5, school: "Abjuration", target: "ally" },
    { id: 'haste', name: "Haste", cost: 10, buff: "Hasted", duration: 5, school: "Transmutation", target: "ally" },
    { id: 'slow', name: "Slow", cost: 10, buff: "Slowed", duration: 5, school: "Transmutation", target: "enemy" },
    { id: 'fly', name: "Fly", cost: 10, buff: "Flying", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'fear', name: "Fear", cost: 10, buff: "Frightened", duration: 3, school: "Illusion", target: "enemy" },
    { id: 'hypnotic_pattern', name: "Hypnotic Pattern", cost: 10, buff: "Hypnotized", duration: 3, school: "Illusion", target: "enemy" },
    { id: 'major_image', name: "Major Image", cost: 9, buff: "Grand Illusion", duration: 5, school: "Illusion", target: "self" },
    { id: 'bestow_curse', name: "Bestow Curse", cost: 10, buff: "Cursed", duration: 5, school: "Necromancy", target: "enemy" },
    { id: 'animate_dead', name: "Animate Dead", cost: 10, buff: "Undead Minion", duration: 24, school: "Necromancy", target: "self" },
    { id: 'stinking_cloud', name: "Stinking Cloud", cost: 9, buff: "Nauseated", duration: 3, school: "Conjuration", target: "enemy" },
    { id: 'sleet_storm', name: "Sleet Storm", cost: 9, damage: 10, school: "Conjuration", target: "enemy" },
    { id: 'plant_growth', name: "Plant Growth", cost: 9, buff: "Overgrown Terrain", duration: 10, school: "Transmutation", target: "self" },
    { id: 'protection_energy', name: "Protection from Energy", cost: 9, buff: "Energy Resistance", duration: 10, school: "Abjuration", target: "ally" },
    { id: 'clairvoyance', name: "Clairvoyance", cost: 10, buff: "Remote Viewing", duration: 5, school: "Divination", target: "self" },
    { id: 'tongues', name: "Tongues", cost: 9, buff: "Universal Speech", duration: 10, school: "Divination", target: "ally" },
 
    // === LEVEL 4 SPELLS (Cost: 13-16) ===
    { id: 'ice_storm', name: "Ice Storm", cost: 14, damage: 32, school: "Evocation", target: "enemy" },
    { id: 'blight', name: "Blight", cost: 14, damage: 36, school: "Necromancy", target: "enemy" },
    { id: 'phantasmal_killer', name: "Phantasmal Killer", cost: 14, damage: 28, school: "Illusion", target: "enemy" },
    { id: 'fire_shield', name: "Fire Shield", cost: 13, damage: 10, school: "Evocation", target: "self" },
    { id: 'vitriolic_sphere', name: "Vitriolic Sphere", cost: 14, damage: 34, school: "Evocation", target: "enemy" },
    { id: 'greater_invisibility', name: "Greater Invisibility", cost: 14, buff: "Greater Invisibility", duration: 5, school: "Illusion", target: "ally" },
    { id: 'polymorph', name: "Polymorph", cost: 15, buff: "Polymorphed", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'banishment', name: "Banishment", cost: 15, buff: "Banished", duration: 5, school: "Abjuration", target: "enemy" },
    { id: 'dimension_door', name: "Dimension Door", cost: 14, buff: "Dimensional Travel", duration: 1, school: "Conjuration", target: "self" },
    { id: 'confusion', name: "Confusion", cost: 14, buff: "Confused", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'compulsion', name: "Compulsion", cost: 14, buff: "Compelled", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'dominate_beast', name: "Dominate Beast", cost: 14, buff: "Beast Dominated", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'freedom_movement', name: "Freedom of Movement", cost: 13, buff: "Unrestricted", duration: 10, school: "Abjuration", target: "ally" },
    { id: 'stoneskin', name: "Stoneskin", cost: 15, buff: "Stone Skin", duration: 10, school: "Abjuration", target: "ally" },
    { id: 'death_ward', name: "Death Ward", cost: 14, buff: "Death Warded", duration: 24, school: "Abjuration", target: "ally" },
    { id: 'locate_creature', name: "Locate Creature", cost: 13, buff: "Creature Tracking", duration: 10, school: "Divination", target: "self" },
    { id: 'arcane_eye', name: "Arcane Eye", cost: 13, buff: "Arcane Vision", duration: 10, school: "Divination", target: "self" },
 
    // === LEVEL 5 SPELLS (Cost: 17-20) ===
    { id: 'cone_cold', name: "Cone of Cold", cost: 18, damage: 42, school: "Evocation", target: "enemy" },
    { id: 'flame_strike', name: "Flame Strike", cost: 18, damage: 38, school: "Evocation", target: "enemy" },
    { id: 'cloudkill', name: "Cloudkill", cost: 18, damage: 30, school: "Conjuration", target: "enemy" },
    { id: 'insect_plague', name: "Insect Plague", cost: 17, damage: 28, school: "Conjuration", target: "enemy" },
    { id: 'destructive_wave', name: "Destructive Wave", cost: 18, damage: 40, school: "Evocation", target: "enemy" },
    { id: 'synaptic_static', name: "Synaptic Static", cost: 18, damage: 36, school: "Enchantment", target: "enemy" },
    { id: 'mass_cure_wounds', name: "Mass Cure Wounds", cost: 18, heal: 25, school: "Evocation", target: "ally" },
    { id: 'greater_restoration', name: "Greater Restoration", cost: 18, heal: 20, school: "Abjuration", target: "ally" },
    { id: 'raise_dead', name: "Raise Dead", cost: 20, heal: 50, school: "Necromancy", target: "ally" },
    { id: 'hold_monster', name: "Hold Monster", cost: 18, buff: "Monster Paralyzed", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'dominate_person', name: "Dominate Person", cost: 18, buff: "Person Dominated", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'telekinesis', name: "Telekinesis", cost: 17, buff: "Telekinetic Control", duration: 5, school: "Transmutation", target: "self" },
    { id: 'animate_objects', name: "Animate Objects", cost: 18, buff: "Animated Servants", duration: 5, school: "Transmutation", target: "self" },
    { id: 'wall_force', name: "Wall of Force", cost: 18, buff: "Force Barrier", duration: 5, school: "Evocation", target: "self" },
    { id: 'wall_stone', name: "Wall of Stone", cost: 17, buff: "Stone Barrier", duration: 10, school: "Evocation", target: "self" },
    { id: 'conjure_elemental', name: "Conjure Elemental", cost: 18, buff: "Elemental Ally", duration: 10, school: "Conjuration", target: "self" },
    { id: 'teleportation_circle', name: "Teleportation Circle", cost: 17, buff: "Portal Open", duration: 1, school: "Conjuration", target: "self" },
    { id: 'scrying', name: "Scrying", cost: 17, buff: "Scrying Vision", duration: 5, school: "Divination", target: "self" },
    { id: 'legend_lore', name: "Legend Lore", cost: 17, buff: "Ancient Knowledge", duration: 1, school: "Divination", target: "self" },
    { id: 'dream', name: "Dream", cost: 17, buff: "Dream Message", duration: 8, school: "Illusion", target: "ally" },
    { id: 'mislead', name: "Mislead", cost: 17, buff: "Illusory Double", duration: 5, school: "Illusion", target: "self" },
    { id: 'modify_memory', name: "Modify Memory", cost: 18, buff: "Memory Altered", duration: 1, school: "Enchantment", target: "enemy" },
    { id: 'geas', name: "Geas", cost: 18, buff: "Geased", duration: 720, school: "Enchantment", target: "enemy" },
    { id: 'antilife_shell', name: "Antilife Shell", cost: 17, buff: "Life Barrier", duration: 10, school: "Abjuration", target: "self" },
    { id: 'dispel_evil', name: "Dispel Evil and Good", cost: 17, buff: "Planar Protection", duration: 5, school: "Abjuration", target: "self" },
];