import { Spell } from '../types';

export const SPELLS_DB: Spell[] = [ 
    // === CANTRIPS (Cost: 1-2) ===
    { id: 'firebolt', name: "Fire Bolt", cost: 2, damage: 8, school: "Evocation", target: "enemy", description: "A mote of fire hurled at a foe." },
    { id: 'ray_frost', name: "Ray of Frost", cost: 2, damage: 6, school: "Evocation", target: "enemy" },
    { id: 'shocking_grasp', name: "Shocking Grasp", cost: 2, damage: 7, school: "Evocation", target: "enemy" },
    { id: 'eldritch_blast', name: "Eldritch Blast", cost: 2, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'sacred_flame', name: "Sacred Flame", cost: 2, damage: 6, school: "Evocation", target: "enemy" },
    { id: 'toll_the_dead', name: "Toll the Dead", cost: 2, damage: 8, school: "Necromancy", target: "enemy" },
    { id: 'chill_touch', name: "Chill Touch", cost: 2, damage: 6, school: "Necromancy", target: "enemy" },
    { id: 'acid_splash', name: "Acid Splash", cost: 2, damage: 5, school: "Conjuration", target: "enemy" },
    { id: 'poison_spray', name: "Poison Spray", cost: 2, damage: 10, school: "Conjuration", target: "enemy" },
    { id: 'produce_flame', name: "Produce Flame", cost: 1, damage: 6, school: "Conjuration", target: "enemy" },
    { id: 'light', name: "Light", cost: 1, buff: "Illuminated", duration: 10, school: "Evocation", target: "self" },
    { id: 'mage_hand', name: "Mage Hand", cost: 1, buff: "Spectral Hand", duration: 5, school: "Conjuration", target: "self" },
    { id: 'prestidigitation', name: "Prestidigitation", cost: 1, buff: "Minor Magic", duration: 3, school: "Transmutation", target: "self" },
    { id: 'minor_illusion', name: "Minor Illusion", cost: 1, buff: "Illusory Distraction", duration: 3, school: "Illusion", target: "self" },
    { id: 'guidance', name: "Guidance", cost: 1, buff: "Guided", duration: 1, school: "Divination", target: "ally" },
    { id: 'resistance', name: "Resistance", cost: 1, buff: "Resistant", duration: 1, school: "Abjuration", target: "ally" },
    { id: 'thaumaturgy', name: "Thaumaturgy", cost: 1, buff: "Intimidating Presence", duration: 2, school: "Transmutation", target: "self" },
    { id: 'druidcraft', name: "Druidcraft", cost: 1, buff: "Nature's Touch", duration: 3, school: "Transmutation", target: "self" },
    { id: 'spare_dying', name: "Spare the Dying", cost: 1, heal: 1, school: "Necromancy", target: "ally" },
    { id: 'blade_ward', name: "Blade Ward", cost: 1, buff: "Warded", duration: 1, school: "Abjuration", target: "self" },
 
    // === LEVEL 1 SPELLS (Cost: 3-5) ===
    { id: 'heal', name: "Cure Wounds", cost: 5, heal: 12, school: "Evocation", target: "ally" },
    { id: 'healing_word', name: "Healing Word", cost: 3, heal: 8, school: "Evocation", target: "ally" },
    { id: 'goodberry', name: "Goodberry", cost: 3, heal: 10, school: "Transmutation", target: "ally" },
    { id: 'shield', name: "Shield", cost: 3, buff: "Shielded", duration: 2, school: "Abjuration", target: "self" },
    { id: 'mage_armor', name: "Mage Armor", cost: 4, buff: "Mage Armor", duration: 8, school: "Abjuration", target: "self" },
    { id: 'sanctuary', name: "Sanctuary", cost: 3, buff: "Sanctuary", duration: 3, school: "Abjuration", target: "ally" },
    { id: 'shield_faith', name: "Shield of Faith", cost: 3, buff: "Faith Shield", duration: 5, school: "Abjuration", target: "ally" },
    { id: 'absorb_elements', name: "Absorb Elements", cost: 3, buff: "Elemental Absorption", duration: 1, school: "Abjuration", target: "self" },
    { id: 'magic_missile', name: "Magic Missile", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'burning_hands', name: "Burning Hands", cost: 4, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'thunderwave', name: "Thunderwave", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'chromatic_orb', name: "Chromatic Orb", cost: 5, damage: 14, school: "Evocation", target: "enemy" },
    { id: 'ice_knife', name: "Ice Knife", cost: 4, damage: 12, school: "Conjuration", target: "enemy" },
    { id: 'inflict_wounds', name: "Inflict Wounds", cost: 5, damage: 16, school: "Necromancy", target: "enemy" },
    { id: 'guiding_bolt', name: "Guiding Bolt", cost: 4, damage: 14, school: "Evocation", target: "enemy" },
    { id: 'hellish_rebuke', name: "Hellish Rebuke", cost: 4, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'witchbolt', name: "Witch Bolt", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'earth_tremor', name: "Earth Tremor", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'sleep', name: "Sleep", cost: 4, buff: "Sleep Aura", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'charm_person', name: "Charm Person", cost: 4, buff: "Charmed", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'command', name: "Command", cost: 3, buff: "Commanded", duration: 1, school: "Enchantment", target: "enemy" },
    { id: 'bane', name: "Bane", cost: 4, buff: "Baned", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'bless', name: "Bless", cost: 4, buff: "Blessed", duration: 5, school: "Enchantment", target: "ally" },
    { id: 'heroism', name: "Heroism", cost: 4, buff: "Heroic", duration: 5, school: "Enchantment", target: "ally" },
    { id: 'faerie_fire', name: "Faerie Fire", cost: 4, buff: "Revealed", duration: 3, school: "Evocation", target: "enemy" },
    { id: 'entangle', name: "Entangle", cost: 4, buff: "Entangled", duration: 3, school: "Conjuration", target: "enemy" },
    { id: 'fog_cloud', name: "Fog Cloud", cost: 3, buff: "Obscured", duration: 5, school: "Conjuration", target: "self" },
    { id: 'grease', name: "Grease", cost: 3, buff: "Slippery Ground", duration: 3, school: "Conjuration", target: "enemy" },
    { id: 'disguise_self', name: "Disguise Self", cost: 3, buff: "Disguised", duration: 10, school: "Illusion", target: "self" },
    { id: 'silent_image', name: "Silent Image", cost: 3, buff: "Illusory Cover", duration: 5, school: "Illusion", target: "self" },
    { id: 'detect_magic', name: "Detect Magic", cost: 3, buff: "Magic Sight", duration: 5, school: "Divination", target: "self" },
    { id: 'identify', name: "Identify", cost: 3, buff: "Identified", duration: 1, school: "Divination", target: "self" },
    { id: 'hunters_mark', name: "Hunter's Mark", cost: 3, buff: "Marked Prey", duration: 10, school: "Divination", target: "enemy" },
    { id: 'hex', name: "Hex", cost: 3, damage: 4, school: "Enchantment", target: "enemy" },
    { id: 'false_life', name: "False Life", cost: 3, heal: 8, school: "Necromancy", target: "self" },
    { id: 'expeditious_retreat', name: "Expeditious Retreat", cost: 3, buff: "Hastened", duration: 5, school: "Transmutation", target: "self" },
    { id: 'jump', name: "Jump", cost: 3, buff: "Enhanced Leap", duration: 3, school: "Transmutation", target: "self" },
    { id: 'longstrider', name: "Longstrider", cost: 3, buff: "Swift", duration: 10, school: "Transmutation", target: "self" },
    { id: 'feather_fall', name: "Feather Fall", cost: 3, buff: "Featherweight", duration: 1, school: "Transmutation", target: "ally" },
 
    // === LEVEL 2 SPELLS (Cost: 6-8) ===
    { id: 'prayer_healing', name: "Prayer of Healing", cost: 8, heal: 18, school: "Evocation", target: "ally" },
    { id: 'lesser_restoration', name: "Lesser Restoration", cost: 6, heal: 5, school: "Abjuration", target: "ally" },
    { id: 'aid', name: "Aid", cost: 6, heal: 10, school: "Abjuration", target: "ally" },
    { id: 'scorching_ray', name: "Scorching Ray", cost: 7, damage: 18, school: "Evocation", target: "enemy" },
    { id: 'shatter', name: "Shatter", cost: 7, damage: 16, school: "Evocation", target: "enemy" },
    { id: 'melfs_acid_arrow', name: "Melf's Acid Arrow", cost: 7, damage: 16, school: "Evocation", target: "enemy" },
    { id: 'spiritual_weapon', name: "Spiritual Weapon", cost: 6, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'moonbeam', name: "Moonbeam", cost: 7, damage: 14, school: "Evocation", target: "enemy" },
    { id: 'flame_blade', name: "Flame Blade", cost: 6, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'cloud_daggers', name: "Cloud of Daggers", cost: 6, damage: 14, school: "Conjuration", target: "enemy" },
    { id: 'ray_enfeeblement', name: "Ray of Enfeeblement", cost: 6, damage: 8, school: "Necromancy", target: "enemy" },
    { id: 'blindness', name: "Blindness/Deafness", cost: 6, buff: "Blinded", duration: 3, school: "Necromancy", target: "enemy" },
    { id: 'mirror_image', name: "Mirror Image", cost: 6, buff: "Mirror Images", duration: 5, school: "Illusion", target: "self" },
    { id: 'invisibility', name: "Invisibility", cost: 7, buff: "Invisible", duration: 5, school: "Illusion", target: "ally" },
    { id: 'blur', name: "Blur", cost: 6, buff: "Blurred", duration: 5, school: "Illusion", target: "self" },
    { id: 'misty_step', name: "Misty Step", cost: 6, buff: "Teleported", duration: 1, school: "Conjuration", target: "self" },
    { id: 'hold_person', name: "Hold Person", cost: 7, buff: "Paralyzed", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'crown_madness', name: "Crown of Madness", cost: 6, buff: "Maddened", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'suggestion', name: "Suggestion", cost: 7, buff: "Suggested", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'calm_emotions', name: "Calm Emotions", cost: 6, buff: "Calmed", duration: 3, school: "Enchantment", target: "ally" },
    { id: 'web', name: "Web", cost: 6, buff: "Webbed", duration: 5, school: "Conjuration", target: "enemy" },
    { id: 'spike_growth', name: "Spike Growth", cost: 7, damage: 10, school: "Transmutation", target: "enemy" },
    { id: 'barkskin', name: "Barkskin", cost: 6, buff: "Barkskin", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'enlarge_reduce', name: "Enlarge/Reduce", cost: 6, buff: "Enlarged", duration: 5, school: "Transmutation", target: "ally" },
    { id: 'heat_metal', name: "Heat Metal", cost: 7, damage: 12, school: "Transmutation", target: "enemy" },
    { id: 'see_invisibility', name: "See Invisibility", cost: 6, buff: "True Sight", duration: 10, school: "Divination", target: "self" },
    { id: 'detect_thoughts', name: "Detect Thoughts", cost: 6, buff: "Mind Reading", duration: 5, school: "Divination", target: "self" },
    { id: 'darkness', name: "Darkness", cost: 6, buff: "Magical Darkness", duration: 5, school: "Evocation", target: "self" },
    { id: 'warding_bond', name: "Warding Bond", cost: 7, buff: "Bonded Protection", duration: 10, school: "Abjuration", target: "ally" },
 
    // === LEVEL 3 SPELLS (Cost: 9-12) ===
    { id: 'fireball', name: "Fireball", cost: 10, damage: 28, school: "Evocation", target: "enemy" },
    { id: 'lightning_bolt', name: "Lightning Bolt", cost: 10, damage: 28, school: "Evocation", target: "enemy" },
    { id: 'call_lightning', name: "Call Lightning", cost: 10, damage: 24, school: "Conjuration", target: "enemy" },
    { id: 'spirit_guardians', name: "Spirit Guardians", cost: 10, damage: 20, school: "Conjuration", target: "enemy" },
    { id: 'vampiric_touch', name: "Vampiric Touch", cost: 10, damage: 18, school: "Necromancy", target: "enemy" },
    { id: 'hunger_hadar', name: "Hunger of Hadar", cost: 10, damage: 16, school: "Conjuration", target: "enemy" },
    { id: 'erupting_earth', name: "Erupting Earth", cost: 9, damage: 20, school: "Transmutation", target: "enemy" },
    { id: 'tidal_wave', name: "Tidal Wave", cost: 9, damage: 18, school: "Conjuration", target: "enemy" },
    { id: 'mass_healing_word', name: "Mass Healing Word", cost: 10, heal: 15, school: "Evocation", target: "ally" },
    { id: 'revivify', name: "Revivify", cost: 12, heal: 30, school: "Necromancy", target: "ally" },
    { id: 'beacon_hope', name: "Beacon of Hope", cost: 9, buff: "Hopeful", duration: 5, school: "Abjuration", target: "ally" },
    { id: 'counterspell', name: "Counterspell", cost: 9, buff: "Spell Negated", duration: 1, school: "Abjuration", target: "enemy" },
    { id: 'dispel_magic', name: "Dispel Magic", cost: 9, buff: "Dispelled", duration: 1, school: "Abjuration", target: "enemy" },
    { id: 'remove_curse', name: "Remove Curse", cost: 9, heal: 5, school: "Abjuration", target: "ally" },
    { id: 'haste', name: "Haste", cost: 10, buff: "Hasted", duration: 5, school: "Transmutation", target: "ally" },
    { id: 'slow', name: "Slow", cost: 10, buff: "Slowed", duration: 5, school: "Transmutation", target: "enemy" },
    { id: 'fly', name: "Fly", cost: 10, buff: "Flying", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'fear', name: "Fear", cost: 10, buff: "Frightened", duration: 3, school: "Illusion", target: "enemy" },
    { id: 'hypnotic_pattern', name: "Hypnotic Pattern", cost: 10, buff: "Hypnotized", duration: 3, school: "Illusion", target: "enemy" },
    { id: 'major_image', name: "Major Image", cost: 9, buff: "Grand Illusion", duration: 5, school: "Illusion", target: "self" },
    { id: 'bestow_curse', name: "Bestow Curse", cost: 10, buff: "Cursed", duration: 5, school: "Necromancy", target: "enemy" },
    { id: 'animate_dead', name: "Animate Dead", cost: 10, buff: "Undead Minion", duration: 24, school: "Necromancy", target: "self" },
    { id: 'stinking_cloud', name: "Stinking Cloud", cost: 9, buff: "Nauseated", duration: 3, school: "Conjuration", target: "enemy" },
    { id: 'sleet_storm', name: "Sleet Storm", cost: 9, damage: 10, school: "Conjuration", target: "enemy" },
    { id: 'plant_growth', name: "Plant Growth", cost: 9, buff: "Overgrown Terrain", duration: 10, school: "Transmutation", target: "self" },
    { id: 'protection_energy', name: "Protection from Energy", cost: 9, buff: "Energy Resistance", duration: 10, school: "Abjuration", target: "ally" },
    { id: 'clairvoyance', name: "Clairvoyance", cost: 10, buff: "Remote Viewing", duration: 5, school: "Divination", target: "self" },
    { id: 'tongues', name: "Tongues", cost: 9, buff: "Universal Speech", duration: 10, school: "Divination", target: "ally" },
 
    // === LEVEL 4 SPELLS (Cost: 13-16) ===
    { id: 'ice_storm', name: "Ice Storm", cost: 14, damage: 32, school: "Evocation", target: "enemy" },
    { id: 'blight', name: "Blight", cost: 14, damage: 36, school: "Necromancy", target: "enemy" },
    { id: 'phantasmal_killer', name: "Phantasmal Killer", cost: 14, damage: 28, school: "Illusion", target: "enemy" },
    { id: 'fire_shield', name: "Fire Shield", cost: 13, damage: 10, school: "Evocation", target: "self" },
    { id: 'vitriolic_sphere', name: "Vitriolic Sphere", cost: 14, damage: 34, school: "Evocation", target: "enemy" },
    { id: 'greater_invisibility', name: "Greater Invisibility", cost: 14, buff: "Greater Invisibility", duration: 5, school: "Illusion", target: "ally" },
    { id: 'polymorph', name: "Polymorph", cost: 15, buff: "Polymorphed", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'banishment', name: "Banishment", cost: 15, buff: "Banished", duration: 5, school: "Abjuration", target: "enemy" },
    { id: 'dimension_door', name: "Dimension Door", cost: 14, buff: "Dimensional Travel", duration: 1, school: "Conjuration", target: "self" },
    { id: 'confusion', name: "Confusion", cost: 14, buff: "Confused", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'compulsion', name: "Compulsion", cost: 14, buff: "Compelled", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'dominate_beast', name: "Dominate Beast", cost: 14, buff: "Beast Dominated", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'freedom_movement', name: "Freedom of Movement", cost: 13, buff: "Unrestricted", duration: 10, school: "Abjuration", target: "ally" },
    { id: 'stoneskin', name: "Stoneskin", cost: 15, buff: "Stone Skin", duration: 10, school: "Abjuration", target: "ally" },
    { id: 'death_ward', name: "Death Ward", cost: 14, buff: "Death Warded", duration: 24, school: "Abjuration", target: "ally" },
    { id: 'locate_creature', name: "Locate Creature", cost: 13, buff: "Creature Tracking", duration: 10, school: "Divination", target: "self" },
    { id: 'arcane_eye', name: "Arcane Eye", cost: 13, buff: "Arcane Vision", duration: 10, school: "Divination", target: "self" },
 
    // === LEVEL 5 SPELLS (Cost: 17-20) ===
    { id: 'cone_cold', name: "Cone of Cold", cost: 18, damage: 42, school: "Evocation", target: "enemy" },
    { id: 'flame_strike', name: "Flame Strike", cost: 18, damage: 38, school: "Evocation", target: "enemy" },
    { id: 'cloudkill', name: "Cloudkill", cost: 18, damage: 30, school: "Conjuration", target: "enemy" },
    { id: 'insect_plague', name: "Insect Plague", cost: 17, damage: 28, school: "Conjuration", target: "enemy" },
    { id: 'destructive_wave', name: "Destructive Wave", cost: 18, damage: 40, school: "Evocation", target: "enemy" },
    { id: 'synaptic_static', name: "Synaptic Static", cost: 18, damage: 36, school: "Enchantment", target: "enemy" },
    { id: 'mass_cure_wounds', name: "Mass Cure Wounds", cost: 18, heal: 25, school: "Evocation", target: "ally" },
    { id: 'greater_restoration', name: "Greater Restoration", cost: 18, heal: 20, school: "Abjuration", target: "ally" },
    { id: 'raise_dead', name: "Raise Dead", cost: 20, heal: 50, school: "Necromancy", target: "ally" },
    { id: 'hold_monster', name: "Hold Monster", cost: 18, buff: "Monster Paralyzed", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'dominate_person', name: "Dominate Person", cost: 18, buff: "Person Dominated", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'telekinesis', name: "Telekinesis", cost: 17, buff: "Telekinetic Control", duration: 5, school: "Transmutation", target: "self" },
    { id: 'animate_objects', name: "Animate Objects", cost: 18, buff: "Animated Servants", duration: 5, school: "Transmutation", target: "self" },
    { id: 'wall_force', name: "Wall of Force", cost: 18, buff: "Force Barrier", duration: 5, school: "Evocation", target: "self" },
    { id: 'wall_stone', name: "Wall of Stone", cost: 17, buff: "Stone Barrier", duration: 10, school: "Evocation", target: "self" },
    { id: 'conjure_elemental', name: "Conjure Elemental", cost: 18, buff: "Elemental Ally", duration: 10, school: "Conjuration", target: "self" },
    { id: 'teleportation_circle', name: "Teleportation Circle", cost: 17, buff: "Portal Open", duration: 1, school: "Conjuration", target: "self" },
    { id: 'scrying', name: "Scrying", cost: 17, buff: "Scrying Vision", duration: 5, school: "Divination", target: "self" },
    { id: 'legend_lore', name: "Legend Lore", cost: 17, buff: "Ancient Knowledge", duration: 1, school: "Divination", target: "self" },
    { id: 'dream', name: "Dream", cost: 17, buff: "Dream Message", duration: 8, school: "Illusion", target: "ally" },
    { id: 'mislead', name: "Mislead", cost: 17, buff: "Illusory Double", duration: 5, school: "Illusion", target: "self" },
    { id: 'modify_memory', name: "Modify Memory", cost: 18, buff: "Memory Altered", duration: 1, school: "Enchantment", target: "enemy" },
    { id: 'geas', name: "Geas", cost: 18, buff: "Geased", duration: 720, school: "Enchantment", target: "enemy" },
    { id: 'antilife_shell', name: "Antilife Shell", cost: 17, buff: "Life Barrier", duration: 10, school: "Abjuration", target: "self" },
    { id: 'dispel_evil', name: "Dispel Evil and Good", cost: 17, buff: "Planar Protection", duration: 5, school: "Abjuration", target: "self" },
    { id: 'steel_wind', name: "Steel Wind Strike", cost: 18, damage: 36, school: "Conjuration", target: "enemy", description: "You flourish your weapon and vanish to strike like the wind." },
    { id: 'bigbys_hand', name: "Bigby's Hand", cost: 18, damage: 24, school: "Evocation", target: "enemy", description: "You create a Large hand of shimmering force." },
    { id: 'dawn', name: "Dawn", cost: 18, damage: 32, school: "Evocation", target: "enemy", description: "A column of divine fire roars down from the heavens." },
    { id: 'enervation', name: "Enervation", cost: 17, damage: 28, school: "Necromancy", target: "enemy", description: "A tendril of darkness reaches out to siphon life force." },
    { id: 'negative_energy_flood', name: "Negative Energy Flood", cost: 18, damage: 40, school: "Necromancy", target: "enemy", description: "You unleash a virulent flood of negative energy." },
    { id: 'skill_empowerment', name: "Skill Empowerment", cost: 17, buff: "Empowered Skills", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'far_step', name: "Far Step", cost: 17, buff: "Dimensional Step", duration: 5, school: "Conjuration", target: "self" },
    { id: 'wrath_nature', name: "Wrath of Nature", cost: 18, damage: 26, school: "Evocation", target: "enemy", description: "The natural world rises up against your enemies." },
    { id: 'holy_weapon', name: "Holy Weapon", cost: 18, buff: "Holy Weapon", duration: 10, school: "Evocation", target: "ally", description: "Your weapon glows with holy radiance." },

    // === LEVEL 6 SPELLS (Cost: 21-25) ===
    { id: 'chain_lightning', name: "Chain Lightning", cost: 23, damage: 52, school: "Evocation", target: "enemy", description: "Lightning arcs from target to target in deadly chains." },
    { id: 'disintegrate', name: "Disintegrate", cost: 25, damage: 75, school: "Transmutation", target: "enemy", description: "A thin green ray springs from your pointing finger to destroy matter." },
    { id: 'circle_death', name: "Circle of Death", cost: 23, damage: 48, school: "Necromancy", target: "enemy", description: "A sphere of negative energy expands from a point you choose." },
    { id: 'sunbeam', name: "Sunbeam", cost: 23, damage: 46, school: "Evocation", target: "enemy", description: "A beam of brilliant light flashes out from your hand." },
    { id: 'harm', name: "Harm", cost: 24, damage: 56, school: "Necromancy", target: "enemy", description: "You unleash a virulent disease on a creature." },
    { id: 'heal', name: "Heal", cost: 24, heal: 70, school: "Evocation", target: "ally", description: "A wave of positive energy washes over a creature." },
    { id: 'blade_barrier', name: "Blade Barrier", cost: 23, damage: 44, school: "Evocation", target: "enemy", description: "You create a vertical wall of spinning blades." },
    { id: 'ottos_dance', name: "Otto's Irresistible Dance", cost: 22, buff: "Dancing Uncontrollably", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'eyebite', name: "Eyebite", cost: 22, buff: "Sickened", duration: 5, school: "Necromancy", target: "enemy" },
    { id: 'mass_suggestion', name: "Mass Suggestion", cost: 22, buff: "Mass Suggested", duration: 24, school: "Enchantment", target: "enemy" },
    { id: 'globe_invuln', name: "Globe of Invulnerability", cost: 23, buff: "Spell Immunity", duration: 5, school: "Abjuration", target: "self" },
    { id: 'true_seeing', name: "True Seeing", cost: 22, buff: "True Sight", duration: 10, school: "Divination", target: "ally" },
    { id: 'word_recall', name: "Word of Recall", cost: 21, buff: "Teleported Home", duration: 1, school: "Conjuration", target: "ally" },
    { id: 'planar_ally', name: "Planar Ally", cost: 24, buff: "Celestial Ally", duration: 10, school: "Conjuration", target: "self" },
    { id: 'find_path', name: "Find the Path", cost: 21, buff: "Pathfinding", duration: 24, school: "Divination", target: "self" },
    { id: 'heroes_feast', name: "Heroes' Feast", cost: 24, heal: 30, school: "Conjuration", target: "ally", description: "You conjure a magnificent feast that cures ailments and bolsters the spirit." },
    { id: 'soul_cage', name: "Soul Cage", cost: 23, buff: "Soul Captured", duration: 8, school: "Necromancy", target: "enemy" },
    { id: 'create_undead', name: "Create Undead", cost: 24, buff: "Undead Servants", duration: 24, school: "Necromancy", target: "self" },
    { id: 'investiture_flame', name: "Investiture of Flame", cost: 23, damage: 20, school: "Transmutation", target: "self", description: "Flames race across your body, shedding light and burning foes." },
    { id: 'investiture_ice', name: "Investiture of Ice", cost: 23, damage: 20, school: "Transmutation", target: "self", description: "Ice covers your body, protecting you and freezing nearby enemies." },
    { id: 'investiture_stone', name: "Investiture of Stone", cost: 23, buff: "Stone Form", duration: 5, school: "Transmutation", target: "self" },
    { id: 'investiture_wind', name: "Investiture of Wind", cost: 23, buff: "Wind Form", duration: 5, school: "Transmutation", target: "self" },
    { id: 'flesh_stone', name: "Flesh to Stone", cost: 24, buff: "Petrifying", duration: 5, school: "Transmutation", target: "enemy" },
    { id: 'mental_prison', name: "Mental Prison", cost: 23, damage: 50, school: "Illusion", target: "enemy", description: "You attempt to bind a creature within an illusory cell." },

    // === LEVEL 7 SPELLS (Cost: 26-30) ===
    { id: 'finger_death', name: "Finger of Death", cost: 28, damage: 86, school: "Necromancy", target: "enemy", description: "You send negative energy coursing through a creature." },
    { id: 'fire_storm', name: "Fire Storm", cost: 28, damage: 56, school: "Evocation", target: "enemy", description: "A storm of fire rains down upon a wide area." },
    { id: 'prismatic_spray', name: "Prismatic Spray", cost: 28, damage: 60, school: "Evocation", target: "enemy", description: "Eight rays of light flash from your hand." },
    { id: 'delayed_fireball', name: "Delayed Blast Fireball", cost: 28, damage: 72, school: "Evocation", target: "enemy", description: "A delayed explosion of searing flame." },
    { id: 'crown_stars', name: "Crown of Stars", cost: 28, damage: 36, school: "Evocation", target: "enemy", description: "Seven star-like motes of light orbit your head." },
    { id: 'divine_word', name: "Divine Word", cost: 28, damage: 40, school: "Evocation", target: "enemy", description: "You utter a divine word imbued with celestial power." },
    { id: 'resurrection', name: "Resurrection", cost: 30, heal: 100, school: "Necromancy", target: "ally", description: "You restore life to a creature that has died within the last century." },
    { id: 'regenerate', name: "Regenerate", cost: 27, heal: 60, school: "Transmutation", target: "ally", description: "You touch a creature and stimulate its natural healing ability." },
    { id: 'reverse_gravity', name: "Reverse Gravity", cost: 27, buff: "Gravity Reversed", duration: 5, school: "Transmutation", target: "enemy" },
    { id: 'forcecage', name: "Forcecage", cost: 28, buff: "Caged", duration: 10, school: "Evocation", target: "enemy" },
    { id: 'teleport', name: "Teleport", cost: 27, buff: "Teleported", duration: 1, school: "Conjuration", target: "ally" },
    { id: 'plane_shift', name: "Plane Shift", cost: 28, buff: "Plane Shifted", duration: 1, school: "Conjuration", target: "ally" },
    { id: 'project_image', name: "Project Image", cost: 27, buff: "Illusory Double", duration: 24, school: "Illusion", target: "self" },
    { id: 'mirage_arcane', name: "Mirage Arcane", cost: 27, buff: "Terrain Illusion", duration: 240, school: "Illusion", target: "self" },
    { id: 'symbol', name: "Symbol", cost: 28, damage: 60, school: "Abjuration", target: "enemy", description: "You inscribe a harmful glyph." },
    { id: 'conjure_celestial', name: "Conjure Celestial", cost: 28, buff: "Celestial Summoned", duration: 10, school: "Conjuration", target: "self" },
    { id: 'etherealness', name: "Etherealness", cost: 27, buff: "Ethereal", duration: 8, school: "Transmutation", target: "self" },
    { id: 'whirlwind', name: "Whirlwind", cost: 28, damage: 48, school: "Evocation", target: "enemy", description: "A whirlwind howls, pulling creatures into its destructive vortex." },
    { id: 'power_word_pain', name: "Power Word Pain", cost: 28, damage: 30, school: "Enchantment", target: "enemy", description: "You speak a word of power that causes waves of intense pain." },

    // === LEVEL 8 SPELLS (Cost: 31-36) ===
    { id: 'sunburst', name: "Sunburst", cost: 34, damage: 84, school: "Evocation", target: "enemy", description: "Brilliant sunlight flashes in a massive sphere." },
    { id: 'earthquake', name: "Earthquake", cost: 34, damage: 50, school: "Evocation", target: "enemy", description: "You create a seismic disturbance." },
    { id: 'incendiary_cloud', name: "Incendiary Cloud", cost: 34, damage: 70, school: "Conjuration", target: "enemy", description: "A swirling cloud of smoke and embers appears." },
    { id: 'abi_dalzims', name: "Abi-Dalzim's Horrid Wilting", cost: 34, damage: 90, school: "Necromancy", target: "enemy", description: "You draw the moisture from every creature in the area." },
    { id: 'power_word_stun', name: "Power Word Stun", cost: 34, buff: "Stunned", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'feeblemind', name: "Feeblemind", cost: 33, damage: 60, school: "Enchantment", target: "enemy", description: "You blast the mind of a creature." },
    { id: 'dominate_monster', name: "Dominate Monster", cost: 34, buff: "Monster Dominated", duration: 10, school: "Enchantment", target: "enemy" },
    { id: 'maze', name: "Maze", cost: 34, buff: "Maze Trapped", duration: 10, school: "Conjuration", target: "enemy" },
    { id: 'demiplane', name: "Demiplane", cost: 33, buff: "Demiplane Portal", duration: 10, school: "Conjuration", target: "self" },
    { id: 'antimagic_field', name: "Antimagic Field", cost: 35, buff: "Antimagic Zone", duration: 10, school: "Abjuration", target: "self" },
    { id: 'holy_aura', name: "Holy Aura", cost: 34, buff: "Holy Aura", duration: 5, school: "Abjuration", target: "ally" },
    { id: 'mind_blank', name: "Mind Blank", cost: 34, buff: "Mind Protected", duration: 24, school: "Abjuration", target: "ally" },
    { id: 'clone', name: "Clone", cost: 35, buff: "Clone Created", duration: 480, school: "Necromancy", target: "self" },
    { id: 'telepathy', name: "Telepathy", cost: 32, buff: "Telepathic Link", duration: 24, school: "Evocation", target: "ally" },
    { id: 'control_weather', name: "Control Weather", cost: 33, buff: "Weather Control", duration: 8, school: "Transmutation", target: "self" },
    { id: 'maddening_darkness', name: "Maddening Darkness", cost: 34, damage: 64, school: "Evocation", target: "enemy", description: "Magical darkness spreads, dealing psychic damage to those within." },
    { id: 'illusory_dragon', name: "Illusory Dragon", cost: 34, damage: 48, school: "Illusion", target: "enemy", description: "You create a Huge illusory dragon." },
    { id: 'dark_star', name: "Dark Star", cost: 35, damage: 72, school: "Evocation", target: "enemy", description: "You create a sphere of devastating gravitational force." },

    // === LEVEL 9 SPELLS (Cost: 37-45) ===
    { id: 'meteor_swarm', name: "Meteor Swarm", cost: 42, damage: 160, school: "Evocation", target: "enemy", description: "Blazing meteors crash to the ground in fiery explosions." },
    { id: 'power_word_kill', name: "Power Word Kill", cost: 42, damage: 200, school: "Enchantment", target: "enemy", description: "You utter a word of power that can compel one creature to die instantly." },
    { id: 'true_resurrection', name: "True Resurrection", cost: 45, heal: 200, school: "Necromancy", target: "ally", description: "You restore to life a creature that has died, even to a new body." },
    { id: 'wish', name: "Wish", cost: 45, heal: 100, school: "Conjuration", target: "ally", description: "The mightiest spell a mortal can cast. State your wish and it may come true." },
    { id: 'gate', name: "Gate", cost: 42, buff: "Planar Gate", duration: 5, school: "Conjuration", target: "self" },
    { id: 'time_stop', name: "Time Stop", cost: 42, buff: "Time Frozen", duration: 3, school: "Transmutation", target: "self" },
    { id: 'true_polymorph', name: "True Polymorph", cost: 42, buff: "True Polymorphed", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'shapechange', name: "Shapechange", cost: 42, buff: "Shapechanged", duration: 10, school: "Transmutation", target: "self" },
    { id: 'foresight', name: "Foresight", cost: 40, buff: "Foresight", duration: 8, school: "Divination", target: "ally" },
    { id: 'imprisonment', name: "Imprisonment", cost: 42, buff: "Imprisoned", duration: 9999, school: "Abjuration", target: "enemy" },
    { id: 'mass_heal', name: "Mass Heal", cost: 42, heal: 150, school: "Evocation", target: "ally", description: "A flood of healing energy flows from you into injured creatures." },
    { id: 'prismatic_wall', name: "Prismatic Wall", cost: 40, buff: "Prismatic Barrier", duration: 10, school: "Abjuration", target: "self" },
    { id: 'astral_projection', name: "Astral Projection", cost: 40, buff: "Astral Form", duration: 24, school: "Necromancy", target: "ally" },
    { id: 'psychic_scream', name: "Psychic Scream", cost: 42, damage: 140, school: "Enchantment", target: "enemy", description: "You unleash a devastating psychic energy that can explode heads." },
    { id: 'blade_disaster', name: "Blade of Disaster", cost: 42, damage: 120, school: "Conjuration", target: "enemy", description: "You create a blade-shaped planar rift that slashes through foes." },
    { id: 'storm_vengeance', name: "Storm of Vengeance", cost: 42, damage: 100, school: "Conjuration", target: "enemy", description: "A churning storm cloud forms, raining destruction from the heavens." },
    { id: 'weird', name: "Weird", cost: 40, damage: 80, school: "Illusion", target: "enemy", description: "You create illusory creatures of each target's deepest fears." },
    { id: 'invulnerability', name: "Invulnerability", cost: 42, buff: "Invulnerable", duration: 3, school: "Abjuration", target: "self" },
    { id: 'ravenous_void', name: "Ravenous Void", cost: 42, damage: 110, school: "Evocation", target: "enemy", description: "You create a 20-foot-radius sphere of destructive gravitational force." },
    { id: 'reality_break', name: "Reality Break", cost: 40, damage: 90, school: "Conjuration", target: "enemy", description: "You shatter the barriers between realities around your target." },
];